export default {
  'serverSuccess.title.202': 'Прийнято',
  'serverSuccess.title.201': 'Створено',
  'serverSuccess.title.100': 'Продовжити',
  'serverSuccess.title.204': 'без вмісту',
  'serverSuccess.title.200': 'OK',
  'serverSuccess.title.206': 'частковий вміст',
  'serverSuccess.title.205': 'скидання вмісту',
  'serverSuccess.title.203': 'неавторизована інформація',

  'serverSuccess.description.202': 'Код стану – 202 Прийнято. Ваш запит був отриманий, але обробка ще не завершена.',
  'serverSuccess.description.201': 'Ваш запит був успішно виконаний і ресурс був створений.',
  'serverSuccess.description.100': 'Процес успішно працює, ви можете продовжити запит чи ігнорувати его, якще це вже зроблено.',
  'serverSuccess.description.204': 'Сервер успішно виконав ваш запит. Немає додаткового контенту для відправки в тіло нагрузки відповіді.',
  'serverSuccess.description.200': 'Ваш запит був технічно коректним, і сервер зміг відповісти і обробити його правильно.',
  'serverSuccess.description.206': 'Ваш запит успішно оброблений, а його тіло містить запрошенные діапазони даних, описані в заголовкові RANGE запиту.',
  'serverSuccess.description.205': 'Запит успішно завершен. Будь ласка, скиньте «вид документу» в початковий стан, в якому воно було отримано з вихідного серверу.',
  'serverSuccess.description.203': 'Ваш запит був успішно оброблений, але прилягаюче до нього корисне навантаження зазнала змін в порівнянні з відповіддю 200 (OK) сервера походженяя за допомогою перетворюючого проксі.',

  'serverInfo.title.300': 'Множинний вибір',
  'serverInfo.title.305': 'використовуй проксі',
  'serverError.title.502': 'Поганий шлюз',
  'serverError.title.400': 'Поганий запис',
  'serverError.title.409': 'Конфлікт',
  'serverError.title.417': 'Очікування не виконано',
  'serverError.title.424': 'Невдала залежність',
  'serverError.title.403': 'Заборонено',
  'serverError.title.504': 'Тайм-аут шлюзу',
  'serverError.title.410': 'Пішов',
  'serverError.title.505': 'Версія HTTP не підтримується',
  'serverError.title.418': 'Я - чайник',
  'serverError.title.419': 'Недостатньо місця на ресурсі',
  'serverError.title.507': 'Недостатньо місця',
  'serverError.title.500': 'Внутрішня помилка серверу',
  'serverError.title.411': 'Потребуемо довжини',
  'serverError.title.423': 'Заблокований',
  'serverError.title.420': 'Метод не піддтримується',
  'serverError.title.405': 'Метод не допускається',
  'serverError.title.301': 'Переміщений назавжди',
  'serverError.title.302': 'Переміщений на певний час',
  'serverError.title.207': 'Мульти статус',
  'serverError.title.511': 'Потрібна аутентифікація мережі',
  'serverError.title.406': 'Неавторизована інформація',
  'serverError.title.404': 'Сторінка не знайдена',
  'serverError.title.501': 'Не виконано',
  'serverError.title.402': 'Потрібна оплата',
  'serverError.title.308': 'Постійне перенаправлення',
  'serverError.title.412': 'Попередня умова не виконана',
  'serverError.title.428': 'Потрібна попередня умова',
  'serverError.title.407': 'потрібна аутентифікація проксі',
  'serverError.title.431': 'поля заголовку запиту надто великі',
  'serverError.title.408': 'тайм-аут запиту',
  'serverError.title.413': 'запит займає надто багато часу',
  'serverError.title.414': 'запитаний uri надто довгий',
  'serverError.title.416': 'запитаний діапазон недопустимий',
  'serverError.title.503': 'сервіс недоступний',
  'serverError.title.101': 'переключення протоколів',
  'serverError.title.429': 'занадто багато запитів',
  'serverError.title.UNAUTHORIZED': 'заборонений',
  'serverError.title.422': 'необроблений ефект',
  'serverError.title.415': 'непідтримуємий тип носія',
  'serverError.title.917': 'категорія не існує',

  'serverError.title.CATEGORY_ALREADY_EXISTS': 'категорія уже існує',
  'serverError.title.MARKET_DOES_NOT_EXISTS': 'позиция не существует',
  'serverError.title.NO_SUCH_CODE': 'не існує такий код',
  'serverError.title.EVENT_DOES_NOT_EXIST': 'подія не існує',
  'serverError.title.INCORRECT_MARKET_CODE': 'невірний код позиції',
  'serverError.title.NOT_SUPPORTED_EVENT_TYPE': 'тип подій не підримується',
  'serverError.title.INCORRECT_SELECTION': 'невірний результат',
  'serverError.title.FOUND_MORE_THAN_ONE_EVENT': 'знайдено більше одної події',
  'serverError.title.EVENT_NOT_FOUND': 'подія не знайдена',
  'serverError.title.PARTICIPANT_NOT_MAPPED': 'учасник не відображений',
  'serverError.title.SPORT_NOT_MAPPED': 'спорт не відображений',
  'serverError.title.COUNTRY_NOT_MAPPED': 'країна не відображена',
  'serverError.title.LEAGUE_NOT_MAPPED': 'ліга не відображена',
  'serverError.title.INCORRECT_SELECTION_TYPE': 'неправильний тип результата',
  'serverError.title.MARKET_ID_IS_MISSING': 'ID позиції відсутній',
  'serverError.title.MAP_ID_IS_MISSING': 'ID карти відустній',
  'serverError.title.QUERY_ERROR': 'помилка запиту',
  'serverError.title.SELECTIONS_MAPPINGS_MISSING': 'маппінг результатів відсутній',
  'serverError.title.SELECTION_MAP_ID_IS_MISSING': 'ID карти результату відсутній',
  'serverError.title.SELECTION_SYSTEM_ID_IS_MISSING': 'ID системи результату відсутній',
  'serverError.title.PROVIDER_SYSTEM_ID_IS_MISSING': 'ID провайдера відсутній',
  'serverError.title.MARKET_MAPPINGS_MISSING': 'маппінг позицій відсутній',
  'serverError.title.MARKET_NOT_MAPPED': 'позиція не відображена',
  'serverError.title.MARKET_NOT_FOUND': 'позиція не знайдена',
  'serverError.title.EVENT_NOT_MAPPED': 'подія не знайдена',
  'serverError.title.SELECTION_NOT_MAPPED': 'результат не відображений',
  'serverError.title.EVENT_MARKET_NOT_MAPPED': 'позиція події не відображена',
  'serverError.title.UNKNOWN_PROVIDER': 'невідомий провайдер',
  'serverError.title.PARTICIPANT_ID_MISSING': 'ID учасника відсутній',
  'serverError.title.INVALID_USER_ID': 'ID недійсного користувача',
  'serverError.title.WRONG_ENTITY': 'неправильний суб\'єкт',
  'serverError.title.USER_ID_MISSING': 'ID користувача відсутній',
  'serverError.title.USER_NOT_FOUND': 'користувач не знайдений',
  'serverError.title.SELECTION_DOES_NOT_EXIST': 'результат не існує',
  'serverError.title.EVENT_MARKET_NOT_FOUND': 'позиція події не знайдена',
  'serverError.title.EVENT_SELECTION_NOT_FOUND': 'результат події не знайдений',
  'serverError.title.INCORRECT_AMOUNT': 'неправильна сума',
  'serverError.title.ACCESS_DENIED': 'доступ заборонений',
  'serverError.title.EVENT_IS_NOT_ACTIVE': 'подія не активна',
  'serverError.title.EVENT_MARKET_IS_NOT_ACTIVE': 'позиція події не активна',
  'serverError.title.EVENT_SELECTION_IS_NOT_ACTIVE': 'результат події не активний',
  'serverError.title.MARKET_IS_NOT_ACTIVE': 'позиція не активна',
  'serverError.title.SPORT_IS_NOT_ACTIVE': 'спорт не активний',
  'serverError.title.COUNTRY_IS_NOT_ACTIVE': 'країна не активна',
  'serverError.title.LEAGUE_IS_NOT_ACTIVE': 'ліга не активна',
  'serverError.title.EVENT_SELECTION_ODD_RESTRICTION': 'результат події має обмеження на коефіцієнтах',
  'serverError.title.COMBINATION_GROUP_RESTRICTION': 'обмеження групи комбінацій',
  'serverError.title.BAD_QUERY': 'поганий запит',
  'serverError.title.CATEGORY_NOT_FOUND': 'категорія не знайдена',
  'serverError.title.UPDATE_DEFAULT_MARKET': 'оновлення позиції за замовчуванням',
  'serverError.title.CATEGORY_NOT_ACTIVE': 'категорія не активна',
  'serverError.title.INACTIVE_USER': 'неактивний користувач',
  'serverError.title.INSUFFICIENT_BALANCE': 'недостатній баланс',
  'serverError.title.INVALID_BET_TYPE': 'недопустимий тип ставки',
  'serverError.title.INVALID_BET_DETAILS': 'данні ставки недійсні',
  'serverError.title.INVALID_STAKE': 'недопустима ставка',
  'serverError.title.EMAIL_TEMPLATE_NOT_FOUND': 'шаблон електроної почти не знайдений',
  'serverError.title.EMAIL_NOT_FOUND': 'электронна почта не знайдена',
  'serverError.title.BLOCKED_USER': 'заблокований користувач',
  'serverError.title.MARKET_IS_NOT_READY_FOR_BETS': 'позиція не готова для ставок',
  'serverError.title.EVENT_HISTORY_ID_DOES_NOT_EXIST': 'ID исторії подій не існує',
  'serverError.title.INVALID_CATEGORY_ID': 'недійсний ID категорії',
  'serverError.title.INVALID_LEAGUE_ID': 'недійсний ID ліги',
  'serverError.title.LEAGUE_TYPE_NOT_FOUND': 'тип ліги не знайдений',
  'serverError.title.MARKET_SELECTION_ALREADY_EXISTS': 'результат позиції уже існує',
  'serverError.title.PARTICIPANT_MEMBER_ID_MISSING': 'ID представника учасника відсутній',
  'serverError.title.PARTICIPANT_MEMBER_NOT_FOUND': 'представник учасника уже існує',
  'serverError.title.PARTICIPANT_NOT_FOUND': 'учасник не знайдений',
  'serverError.title.WRONG_PARTICIPANT_TYPE': 'неправильний тип учасника',
  'serverError.title.MARKET_ALREADY_EXISTS': 'позиція уже існує',
  'serverError.title.INVALID_TRADING_MODE': 'недійсний режим',
  'serverError.title.INVALID_SETTINGS': 'недійсні налаштування',
  'serverError.title.INVALID_CODE': 'невірний код',
  'serverError.title.INVALID_CATEGORY_TYPE': 'недійсний тип категорії',
  'serverError.title.MARKET_IS_NOT_IN_LEAGUE': 'позиції немає в лізі',
  'serverError.title.INVALID_EMAIL': 'невірна адреса електронной почти',
  'serverError.title.INVALID_USERNAME': 'неверне им\'я користувача',
  'serverError.title.WRONG_USERNAME_PASSWORD': 'Невірне ім\'я користувача і пароль',
  'serverError.title.HASH_IS_NOT_STRING': 'хеш не в строчці',
  'serverError.title.REQUEST_ALREADY_SENT': 'запит уже відправлений',
  'serverError.title.EXPIRED': 'вичерпаний',
  'serverError.title.INVALID_STRING': 'невірний рядок',
  'serverError.title.DUPLICATE': 'копія',
  'serverError.title.INVALID_AMOUNT': 'недопустима сума',
  'serverError.title.INVALID_PERMISSIONS': 'невірні дезволи',
  'serverError.title.EVENT_MISSING_START_DATE': 'в події відсутная дата початку',
  'serverError.title.MORE_THAN_ONE_EVENT_FOUND': 'було знайдено більше одної події',
  'serverError.title.WRONG_PARTICIPANT': 'неправильний учасник',
  'serverError.title.UNKNOWN_TABLE': 'невідома таблиця',
  'serverError.title.INVALID_MAPPING': 'недійсний мапінг',
  'serverError.title.MAPPING_NOT_FOUND': 'мапінг не знайдений',
  'serverError.title.LEAGUE_MAPPING_NOT_FOUND': 'мапінг ліги не знайдений',
  'serverError.title.NOT_MAPPED': 'не відображений',
  'serverError.title.PARTICIPANT_IS_NOT_IN_LEAGUE': 'учасник не в лізі',
  'serverError.title.SELECTION_FIXED_MIN_INVALID': 'недійсна мінімальна кількість результатів',
  'serverError.title.SELECTION_FIXED_MAX_INVALID': 'максимальна кількість результатів',
  'serverError.title.SELECTION_FIXED_MIN_MAX_CONFLICT': 'помилка між мінімальною і максимальною кількістю результатів',
  'serverError.title.INVALID_RULE': 'недійсне правило',
  'serverError.title.RESULT_NOT_FOUND': 'результат не знайдений',
  'serverError.title.MARKET_COMBINATION_MAX_ERROR': 'помилка максимальних позиційних комбінацій',
  'serverError.title.MARKET_COMBINATION_MIN_ERROR': 'помилка мінімальних позиційних комбінацій',
  'serverError.title.MARKET_SETTING_DOES_NOT_EXIST': 'налаштування позиції не існує',
  'serverError.title.SPORT_COMBINATION_MAX_ERROR': 'помилка максимальних комбінацій спорту',
  'serverError.title.SPORT_COMBINATION_MIN_ERROR': 'помилка мінімальних комбінацій спорту',
  'serverError.title.COUNTRY_COMBINATION_MAX_ERROR': 'помилка мінімальних комбінацій країни',
  'serverError.title.COUNTRY_COMBINATION_MIN_ERROR': 'помилка мінімальних комбінацій країни',
  'serverError.title.LEAGUE_COMBINATION_MAX_ERROR': 'помилка максимальних комбінацій ліги',
  'serverError.title.LEAGUE_COMBINATION_MIN_ERROR': 'помилка мінімальних комбінацій ліги',
  'serverError.title.CHANNEL_MISSING': 'канал відсутній',
  'serverError.title.WRONG_CHANNEL': 'неправильний канал',
  'serverError.title.EVENT_RESTRICTED_BET': 'обмеження на типи ставок для подій',
  'serverError.title.LEAGUE_RESTRICTED_BET': 'обмеження на типи ставок для ліг',
  'serverError.title.COUNTRY_RESTRICTED_BET': 'обмеження на типи ставок для країн',
  'serverError.title.SPORT_RESTRICTED_BET': 'обмеження на типи ставок для спорту',
  'serverError.title.POSSIBLE_WIN_MORE_THAN_OVERASK': 'можливий выиграш більший ніж перевантаження',
  'serverError.title.POSSIBLE_WIN_LESS_THAN_OVERASK': 'можливий выиграш менший ніж перевантаження',
  'serverError.title.BET_IN_REVIEW': 'ставка на розгляді',
  'serverError.title.STAKE_MORE_THAN_OVERASK': 'ставка більша ніж перевантаження',
  'serverError.title.STAKE_LESS_THAN_OVERASK': 'ставка менша ніж перевантаження',
  'serverError.title.OVERASK_WRONG_SETTINGS': 'неправильні налаштування перевантаження',
  'serverError.title.USER_STAKE_LIMIT_ERROR': 'помилка - обмеження суми ставки користувача',
  'serverError.title.USER_WON_LIMIT_ERROR': 'помилка - обмеження виграной суми користувача',
  'serverError.title.BET_WON_LIMIT_ERROR': 'помилка – обмеження суми виграшної ставки',
  'serverError.title.BET_STAKE_LIMIT_ERROR': 'помилка – обмеження суми ставки',
  'serverError.title.SELECTION_MIXED_MULTIPLES_ERROR': 'помилка результатів експрес ставки',
  'serverError.title.MARKET_MIXED_MULTIPLES_ERROR': 'помилка позицій експрес ставки',
  'serverError.title.LEAGUE_MIXED_MULTIPLES_ERROR': 'помилка позицій експрес ставки',
  'serverError.title.COUNTRY_MIXED_MULTIPLES_ERROR': 'помилка країни експрес ставки',
  'serverError.title.SPORT_MIXED_MULTIPLES_ERROR': 'помилка спорту експрес ставки',
  'serverError.title.BET_LIMIT_WRONG_SETTINGS': 'неправильні налаштування межі ставки',
  'serverError.title.INVALID_DYNAMIC_LIMIT': 'недійсні динамічні ліміти',
  'serverError.title.CATEGORY_MAPPING_NOT_FOUND': 'маппінг категорії не знайдений',
  'serverError.title.SELECTION_SETTING_DOES_NOT_EXIST': 'налаштування результату не існує',
  'serverError.title.SELECTION_COMBINATION_MIN_ERROR': 'помилка мінімальних комбінацій результатів',
  'serverError.title.SELECTION_COMBINATION_MAX_ERROR': 'помилка максимальних комбінацій результатів',
  'serverError.title.INVALID_CURRENCY': 'недійсна валюта',
  'serverError.title.EVENT_SELECTION_SETTINGS_NOT_FOUND': 'налаштування результату події не знайдені',
  'serverError.title.EVENT_MARKET_SETTINGS_NOT_FOUND': 'налаштування позиції події не знайдені',
  'serverError.title.INVALID_FIRST_NAME': 'недопустиме им\'я',
  'serverError.title.INVALID_LAST_NAME': 'недопустиме прізвище',
  'serverError.title.INVALID_BIRTHDAY': 'невірний день нарождення',
  'serverError.title.INVALID_COUNTRY': 'недопустима країна',
  'serverError.title.INVALID_ADDRESS': 'невірна адреса',
  'serverError.title.INVALID_CITY': 'недопустиме місто',
  'serverError.title.INVALID_STATE': 'невірна область чи невірний край',
  'serverError.title.INVALID_ZIP_CODE': 'неверний почтовий індекс',
  'serverError.title.INVALID_PHONE': 'неправильний номер телефону',
  'serverError.title.INVALID_PASSWORD': 'неправильний пароль',
  'serverError.title.INVALID_ANSWER': 'невірна віповідь',
  'serverError.title.INVALID_AGE_18': 'недопустимий вік 18',
  'serverError.title.INVALID_SECRET': 'недійсний секрет',
  'serverError.title.USER_ALREADY_EXISTS': 'користувач уже існує',
  'serverError.title.PHONE_ALREADY_EXISTS': 'номер телефону уже існує',
  'serverError.title.USERNAME_ALREADY_EXISTS': 'им\'я користувача уже існує',
  'serverError.title.EMAIL_ALREADY_EXISTS': 'адреса електронної почти уже існує',
  'serverError.title.INVALID_QUESTION': 'невірне питання',
  'serverError.title.USER_HASH_IS_NOT_FOUND': 'хеш користувача не знайдений',
  'serverError.title.USER_HASH_IS_EXPIRED': 'хеш користувача минув',
  'serverError.title.EVENT_HAS_ACTIVE_BET': 'подія має активну ставку',
  'serverError.title.EVENT_MARKET_HAS_ACTIVE_BET': 'позиція події має активну ставку',
  'serverError.title.EVENT_SELECTION_HAS_ACTIVE_BET': 'результат події має активну ставку',
  'serverError.title.SMS_CODE_IS_INVALID': 'невірний смс-код',
  'serverError.title.SMS_CODE_IS_EXPIRED': 'строк дії смс-коду минув',
  'serverError.title.SMS_CODE_SENT': 'смс-код відправлений',
  'serverError.title.SMS_CODE_IS_OFF': 'смс-код відключений',
  'serverError.title.EVENT_SETTINGS_DO_NOT_EXIST': 'налаштування події не існують',
  'serverError.title.MARKET_HAS_ACTIVE_BET': 'позиція має активну ставку',
  'serverError.title.USER_NOT_VERIFIED': 'користувач не підтверджений',
  'serverError.title.CURRENCY_NOT_SUPPORTED': 'валюта не підтримується',
  'serverError.title.TRANSACTION_NOT_FOUND': 'транзакція не знайдена',
  'serverError.title.WRONG_WEBSITE_ID': 'неправильний ID сайту',
  'serverError.title.PAYMENT_METHOD_NOT_SUPPORTED_FOR_THIS_WEBSITE': 'метод оплати не підтримуеться для цього сайту',
  'serverError.title.UNKNOWN_FILTER': 'невідомий фільтр',
  'serverError.title.INVALID_DOMAIN': 'неідйсний домен',
  'serverError.title.BET_IS_NOT_IN_REVIEW': 'ставка не на розгляді',
  'serverError.title.INVALID_STATUS': 'недійсний статус',
  'serverError.title.SCOPE_OR_STAT_NOT_FOUND': 'область використання чи статус не знайдені',
  'serverError.title.PAYMENT_NOT_FOUND': 'платіж не знайдений',
  'serverError.title.WEBSITE_NOT_FOUND': 'сайт не знайдений',
  'serverError.title.PAYMENT_DOES_NOT_SUPPORT_SELECTED_CURRENCY': 'метод оплаты не підтримує вибрану валюту',
  'serverError.title.INVALID_IP': 'невірна ip-адреса',
  'serverError.title.COMMUNICATION_ERROR': 'помилка звязку',
  'serverError.title.PURSE_NOT_FOUND': 'гаманець не знайдений',
  'serverError.title.BANNER_ID_MISSING': 'ID баннера відсутній',
  'serverError.title.INVALID_REGISTRATION': 'неправильна регістрація',
  'serverError.title.INVALID_PAYMENT_DETAILS': 'неправильні дані платежу',
  'serverError.title.INSUFFICIENT_MERCHANT_FUNDS': 'торгові коштів недостатньо',
  'serverError.title.SOME_ELSE_EVENT_AT_THIS_TIME_SELECTED': 'в цей час була выбрана інша подія',
  'serverError.title.SESSION_NOT_FOUND': 'сессія не знайдена',
  'serverError.title.CASINO_GAME_NOT_FOUND': 'казино гра не знайдена',
  'serverError.title.PAYMEGA_API_AUTH_ERROR': 'помилка аутентифікації paymega api',
  'serverError.title.PAYMEGA_API_SETTLE_ERROR': 'помилка розрахунку paymega api',
  'serverError.title.TRANSACTION_AUTH_FAILED': 'помилка аутентифікації транзакції',
  'serverError.title.TRANSACTION_SETTLE_FAILED': 'разрахунок транзакції не виконаний',
  'serverError.title.TRANSACTION_CHECK_FAILED': 'перевірка транзакції не вдалась',
  'serverError.title.TRANSACTION_VOID_FAILED': 'анулювання транзакції не виконано',
  'serverError.title.UNKNOWN_DOMAIN': 'невідомий домен',
  'serverError.title.UNKNOWN_EMAIL_TEMPLATE': 'невідомий шаблон електронной пошти',
  'serverError.title.CASINO_ID_IS_INVALID': 'ID казино недійсний',
  'serverError.title.PASSWORD_LENGTH_6': 'довжина пароля 6',

  'serverError.title.INVALID_TRANSACTION_DETAILS': 'данні транзакції недійсні',
  'serverError.title.PHONE_VERIFICATION_FAILED': 'верифікация номера телефона не вдалось',
  'serverError.title.WITHDRAW_MIN_LIMIT': 'мінімальний ліміт виведення',
  'serverError.title.WITHDRAW_MAX_LIMIT': 'максимальний ліміт виведення',
  'serverError.title.DEPOSIT_MIN_LIMIT': 'мінімальний ліміт депозиту',
  'serverError.title.DEPOSIT_MAX_LIMIT': 'максимальний ліміт депозиту',
  'serverError.title.REGISTRATION_EMAIL_SEND_BUT_NOT_VERIFIED': 'регістраційний email відправлений, але не підтверджений',
  'serverError.title.ACTIVE_BETS_ON_EVENT': 'активні ставки на подію',
  'serverError.title.VERIFIED_DOCUMENT_CANNOT_BE_DELETED': 'підтверджений документ не может бути видалений',
  'serverError.title.FIELD_IS_BLOCKED_TO_EDIT': 'поле заблоковано для змін',
  'serverError.title.INVALID_SOCIAL_ID': 'соціальний ID недійсний',

  'serverError.title.EVENT_MARKET_MAX_WINNERS': 'позиція події має максимальну кількість переможців',
  'serverError.title.DOCUMENT_WAS_DELETED_BY_USER': 'документ був видалений користувачем',
  'serverError.title.AGE_FROM_IS_NOT_NUMBER': '‘вік до’ не число',
  'serverError.title.AGE_FROM_IS_LESS_THAN_18': '‘вік від’ менше 18-ти',
  'serverError.title.AGE_TO_IS_NOT_NUMBER': '‘вік до’ не число',
  'serverError.title.AGE_TO_IS_NOT_BETWEEN_18_AND_100': '‘вік до’ не між 18 і 100',
  'serverError.title.AGE_TO_IS_LESS_THAN_AGE_FROM': '‘вік до’ менше ‘вік від’ ',
  'serverError.title.INVALID_DATE': 'недійсна дата',

  'serverError.description.502': 'Помилка сервера: Ваш запит не може бути завершений, так як проксі-сервер наткнувся на тимчасову помилку.',
  'serverError.description.400': 'Ваш браузер відправив запит, який сервер не може зрозуміти. Розмір поля заголовку запиту перевищує ліміт сервера.',
  'serverError.description.409': 'У вашого запиту був недопустимий заголовок ідентифікатора сеансу. Повторіть спробу пізніше чи зверніться до системного адміністратора.',
  'serverError.description.417': 'Очікування, вказане в запиті с заголовком Expect, не може бути виконано сервером.',
  'serverError.description.424': 'Ваш запит не може бути обраблений в результаті вімови попереднього запиту. Будь ласка, спробуйте ще раз!',
  'serverError.description.403': 'У вас немає дозволу на доступ до серверу.',
  'serverError.description.504': 'Сталася помилка ТАЙМ-АУТ ШЛЮЗУ, через яку сервер недоступний. Будь ласка, повторіть запит!',
  'serverError.description.410': `Сторінка не існує чи була видалена. 
                                  Запитане вами джерело недоступно на цьому сервері, і у нас немає адреси пересилання. Це може бути через деякі причини: 
                                    <ul>
                                        <li>Введена вами веб-адреса невірна чи, </li>
                                        <li>Сторінка, яку ви шукаєте, була видалена назавжди.</li>
                                    </ul>
                                  Повторіть спробу чи зверніться до адміністратора серверу.  
                                 `,
  'serverError.description.505': 'Версія HTTP, що використовується в вашому запиті, недійсна чи не підтримується нашим сервером. Будь ласка, спробуйте ще раз!',
  'serverError.description.418': 'Запитаний об\'єкт є коротким і товстим. Підніміть мене і вилейте. Ваш запит на кофе був відхилений, через те, що наш сервер є чайником.',
  'serverError.description.419': 'Сталася неочікувана помилка, що означає, що для виконання операції недостатньо місця на диску. Перевірьте журнал серверу для отримання більш докладноі інформації.',
  'serverError.description.507': 'Сервер не може зберегти данні, необхідні для виконання і завершення вашого запиту.',
  'serverError.description.500': 'Сервер наткнувся на внутрішню помилку чи неправильну конфігурацію, через яку завершення вашого запиту було перервано. Будь ласка, зв\'яжіться з адміністратором серверу для рішення проблеми.',
  'serverError.description.411': 'Сервер відмовляється прийняти ваш запит без певної довжини контенту. Вы можете спробувати відправити запит ще раз, якщо додано допустиме поле заголовку Content-Length з відповідним тілом повідомлення в повідомленні запиту. ',
  'serverError.description.423': 'Сервер відмовляється обробляти запит, так як один із необхідних ресурсів заблокований.',
  'serverError.description.420': 'Сталась системна помилка. Причиною цього може бути пошкодження файлів вашої системи Windows. Повторіть спробу відправки запиту чи зверніться до адміністратора серверу.',
  'serverError.description.405': 'Метод, вказаний в рядку запиту, не дозволений для ресурсу, ідентифікованого Request-URI.',
  'serverError.description.301': 'Запитаному ресурсу був приписаний новий постійний URI, тому будь-які додаткові посилання на ресурс мають використовувати один з повернених URI.',
  'serverError.description.302': 'Була помилка під час з\'єднання з сервером. Запитаний ресурс тимчасово знаходиться під іншим URI. Оскільки перенаправлення може іноді змінюватися, продовжуйте використовувати Request-URI для майбутніх запитів.',
  'serverError.description.207': 'При спробі обробити ваш запит, сталась помилка. Здається, що було виконано кілька операцій, і ви можете знайти статус для кожної операції в тілі відповіді.',
  'serverError.description.511': 'Вам необхідно пройти процесс аутентифікації, щоб отримати доступ до мережі.',
  'serverError.description.406': 'Ваш запит не є допустимим. Співпадюча відповідь запрошеного ресурсу не знайдена на цьому сервері.',
  'serverError.description.404': 'При спробі обробити ваш запит сталася помилка. Сервер не зміг знайти те, що ви запитали.',
  'serverError.description.501': 'При обробці вашого запиту сталася помилка сервера. Сервер чи не розпізнає метод вашого запиту, чи не виконує функції его виконання.',
  'serverError.description.402': 'Сервер наткнувся на внутрішню помилку чи неправильну конфігурацію и не зміг обробити ваш запит. Будь ласка, зв\'яжіться з адміністратором серверу і повідомте йому про час помилка, а також про дії, які ви зробили до того, як це сталося. Журнал помилок серверу також може надати вам додаткову інформацію по цьому питанню. ',
  'serverError.description.412': 'Ваш запит не иоже бути оброблений через передумови, задані в заголовкові запиту. Ці попередні умови не дозволяють застосувати запитаний метод до ресурсу, за виключенням того, що призначено.',
  'serverError.description.308': 'Запитана сторінка була постійно переміщена. ',
  'serverError.description.407': 'Сервер не може виконати запит, оскільки вам не вистачає необхідних облікових даних для проксі-серверу.',
  'serverError.description.428': 'Сервер потребує, щоб ваш запит був умовним (відповідав деяким попередньо заданним умовам). Як правило, це означає, що необхідний заголовок попередньої умови, наприклад, If-Match відсутній.',
  'serverError.description.431': 'Сервер не бажає обробляти ваш запит, тому що поля заголовку надто великі. Якщо зменшити розмір полів заголовку запиту, то запит може бути повторно відправлений і оброблений до завершення. ',
  'serverError.description.408': 'Ваш браузер не зміг відправити повний запит вчасно, тому запит був перерваний сервером. Будь ласка, зв\'яжіться з адміністратором серверу, щоб продовжити процес «Час очікування з\'єднання», якщо ви вважаєте, що ваш запит не повинен був бути вимкнений.',
  'serverError.description.413': 'При спробі обробити ваш запит сталась помилка. Запитаний ресурс не дозволяє запитувати дані з запитами POST чи об\'єм даних, представлених в запиті, перевищує обмеження ємності. ',
  'serverError.description.414': `URI, до якого ви хочете отримати доступ, надто довгий.`,
  'serverError.description.416': 'Запитані діапазони не можуть обслуговуватися сервером, тому що, чи ваш документ не містить заданих діапазонів, чи значення заголовка RANGE несумісно з будь-яким відповідним значенням.',
  'serverError.description.503': 'Сервер тимчасово перестав приймати нові запити, через надто довгу чергу запитів. Будь ласка, спробуйте пізніше.',
  'serverError.description.101': 'Запитуємий вами протокол перемикеється сервером. Було відправлено повідомлення, в яке входить заголовок запиту UPGRADE.',
  'serverError.description.429': 'Ваш IP-адрес викликав надто багато запитів до поточної служби за короткий проміжок часу. Будь ласка, спробуйте пізніше.',
  'serverError.description.UNAUTHORIZED': 'В результаті недопустимих облікових даних забороняється доступ до сторінки чи каталогу.',
  'serverError.description.422': 'Запитана зміна не може бутт опрацьована чи відхилена.',
  'serverError.description.415': 'Ваш запит був відхилений через тк, що ресурс був в форматі, який не підтримується сервером.',
  'serverError.description.917': 'При спробі обробити ваш запит сталася помилка. Повторіть спробу пізніше чи зв\'яжіться з адміністратором сервера для отримання додаткових інструкцій.',

  'serverError.description.CATEGORY_ALREADY_EXISTS': 'Категорія з таким іменем уже існує.',
  'serverError.description.MARKET_DOES_NOT_EXISTS': 'Позиція, яку ви шукаєте, не існує.',
  'serverError.description.NO_SUCH_CODE': 'Ми не змогли знайти відповідну відповідь на введений вами код.',
  'serverError.description.EVENT_DOES_NOT_EXIST': 'Подія, яку ви шукаєте, не існує.',
  'serverError.description.INCORRECT_MARKET_CODE': 'Введений невірний код позиції.',
  'serverError.description.NOT_SUPPORTED_EVENT_TYPE': 'Тип події, який ви створюєт чи вибираєте, не підтримується системою.',
  'serverError.description.INCORRECT_SELECTION': 'Введене вами ім\'я результату невірне.',
  'serverError.description.FOUND_MORE_THAN_ONE_EVENT': 'Ми знайшли більше одної події, відпвідної до вашого запиту.',
  'serverError.description.EVENT_NOT_FOUND': 'Неможливо знайти подію, яку ви шукаєте.',
  'serverError.description.PARTICIPANT_NOT_MAPPED': 'Учасник не був відображений і доданий в відповідну позицію через відсутність необхідних ресурсів.',
  'serverError.description.SPORT_NOT_MAPPED': 'Спорт не був відображений і доданий в відповідну позицію через відсутність необхідних ресурсів.',
  'serverError.description.COUNTRY_NOT_MAPPED': 'Країна не була відображена і додана в відповідну позицію через відсутність необхідних ресурсів.',
  'serverError.description.LEAGUE_NOT_MAPPED': 'Ліга не була відображена і додана в відповідну позицію через відсутність необходних ресурсів.',
  'serverError.description.INCORRECT_SELECTION_TYPE': 'Ви ввели неправильний тип результату.',
  'serverError.description.MARKET_ID_IS_MISSING': 'Ви не визначили ID позиції.',
  'serverError.description.MAP_ID_IS_MISSING': 'Ви не визначили ID карти.',
  'serverError.description.QUERY_ERROR': 'При спробі обробити ваш запит виникла помилка.',
  'serverError.description.SELECTIONS_MAPPINGS_MISSING': 'Маппінг результатів відсутній і повинен бути доданий.',
  'serverError.description.SELECTION_MAP_ID_IS_MISSING': 'Ви не визначили ID карти результату.',
  'serverError.description.SELECTION_SYSTEM_ID_IS_MISSING': 'Ви не визначили ID системи результату.',
  'serverError.description.PROVIDER_SYSTEM_ID_IS_MISSING': 'Ви не визначили ID провайдера.',
  'serverError.description.MARKET_MAPPINGS_MISSING': 'Маппінг позицій відсутній і повинен бути доданий.',
  'serverError.description.MARKET_NOT_MAPPED': 'Позиція не була відображена и додана в відповідну позицію через відсутність необхідних ресурсів.',
  'serverError.description.MARKET_NOT_FOUND': 'Позиція, яку вы шукаєте, не знайдена.',
  'serverError.description.EVENT_NOT_MAPPED': 'Подія не була відображена и додана в відповідну позицію через відсутність необхідних ресурсів.',
  'serverError.description.SELECTION_NOT_MAPPED': 'Результат не був відображений і доданий в відповідну позицію через відсутність необхідних ресурсів.',
  'serverError.description.EVENT_MARKET_NOT_MAPPED': 'Позиція не була відображена і додана в відповідну позицію через відсутність необхідних ресурсів.',
  'serverError.description.UNKNOWN_PROVIDER': 'Провайдер якого ви выбрали, невідомий системі.',
  'serverError.description.PARTICIPANT_ID_MISSING': 'ID учасника відсутній і його необхідно додати.',
  'serverError.description.INVALID_USER_ID': 'ID користувача, якого ви выбрали чи якого ви шукаєте, недійсний або уже існує в системі/не знайдений.',
  'serverError.description.WRONG_ENTITY': 'Введенний вами суб\'єкт помилковий чи недоступний чи суб\'єкт, якого ви вибрали, не відповідає списку суб\'ектів і/або правилам системи. ',
  'serverError.description.USER_ID_MISSING': 'ID користувача повинен бути доданий, оскільки він ще не визначений і відсутній.',
  'serverError.description.USER_NOT_FOUND': 'Користувач, яклшл ви шукаєте, не знайдений.',
  'serverError.description.SELECTION_DOES_NOT_EXIST': 'Результат, який ви шукаєте не існує в системі.',
  'serverError.description.EVENT_MARKET_NOT_FOUND': 'Неможливо знайти позицію події, яку ви шукаєте.',
  'serverError.description.EVENT_SELECTION_NOT_FOUND': 'Результат події, який вы шукаєте не знайдений.',
  'serverError.description.INCORRECT_AMOUNT': 'Введена вами сума невірна.',
  'serverError.description.ACCESS_DENIED': 'Нажаль, ви не можете отримати доступ до наступних даних, чи до наступного разділу, або до наступной інформації. ',
  'serverError.description.EVENT_IS_NOT_ACTIVE': 'Подія, яку ви намагаєтеся відкрити, більше неактивна.',
  'serverError.description.EVENT_MARKET_IS_NOT_ACTIVE': 'Позиція події, до якої ви намагаєтеся отримати доступ, більше не активна.',
  'serverError.description.EVENT_SELECTION_IS_NOT_ACTIVE': 'Результат події, до якого ви намагаєтеся отримати доступ, більше не активний.',
  'serverError.description.MARKET_IS_NOT_ACTIVE': 'Позиція, до якої ви намагаєтеся отримати доступ, більше не активна.',
  'serverError.description.SPORT_IS_NOT_ACTIVE': 'Наступний вид спорту більше не активний.',
  'serverError.description.COUNTRY_IS_NOT_ACTIVE': 'Країна, яку ви хочете ввести або вибрати, неактивна.',
  'serverError.description.LEAGUE_IS_NOT_ACTIVE': 'Ліга, до якої ви хочете отримати доступ, більше не активна.',
  'serverError.description.EVENT_SELECTION_ODD_RESTRICTION': 'Ви досягли найвищой точки обмежень на коефіцієнтах результатів події.',
  'serverError.description.COMBINATION_GROUP_RESTRICTION': 'Вы досягли максимальної кількості груп комбінацій.',
  'serverError.description.BAD_QUERY': 'При спробі обробити ваш запит виникла помилка. Будь ласка, спробуйте ще раз.',
  'serverError.description.CATEGORY_NOT_FOUND': 'Категорія, яку ви шукаєте, не знайдена.',
  'serverError.description.UPDATE_DEFAULT_MARKET': 'Обновіть позицію за замовчуваням.',
  'serverError.description.CATEGORY_NOT_ACTIVE': 'Вибрана вами категорія більше не активна або категорія, яку ви вибрали, поки неактивна.',
  'serverError.description.INACTIVE_USER': 'Користувач, якого ви шукаєте, більше не активний або користувач, якого ви вибрали, поки неактивний.',
  'serverError.description.INSUFFICIENT_BALANCE': 'Для обробки запиту Ваш баланс недостатній.',
  'serverError.description.INVALID_BET_TYPE': 'Тип ставки, ввдений вами, недійсний чи більше не доступний. ',
  'serverError.description.INVALID_BET_DETAILS': 'Введені вами дані ставки недійсні. Будь ласка, виправте їх.',
  'serverError.description.INVALID_STAKE': 'Поставлена вами ставка недійсна і не може быть прийнята.',
  'serverError.description.EMAIL_TEMPLATE_NOT_FOUND': 'Не вдалося знайти шаблон электронної пошти, який ви шукаєте. Можливо, він був видалений по певним причинам.',
  'serverError.description.EMAIL_NOT_FOUND': 'Не вдалося знайти адресу електронної пошти, яку ви шукаєте чи вказали.',
  'serverError.description.BLOCKED_USER': 'Користувач, якого ви шукаєте, заблокований за порушення правил і політики сайту.',
  'serverError.description.MARKET_IS_NOT_READY_FOR_BETS': 'Наступна позиція ще не доступна для ставок.',
  'serverError.description.EVENT_HISTORY_ID_DOES_NOT_EXIST': 'ID історії подій, який ви ввели, не існує і повинен бути доданим.',
  'serverError.description.INVALID_CATEGORY_ID': 'ID категорії, який ви ввели, недійсний.',
  'serverError.description.INVALID_LEAGUE_ID': 'ID ліги введений вами, недійсний.',
  'serverError.description.LEAGUE_TYPE_NOT_FOUND': 'Тип ліги, який ви шукаєте, не знайдений.',
  'serverError.description.MARKET_SELECTION_ALREADY_EXISTS': 'Результат позиції, який ви намагаєтеся створити, уже існує.',
  'serverError.description.PARTICIPANT_MEMBER_ID_MISSING': 'ID представника учасника відсутній і його необхідно додати.',
  'serverError.description.PARTICIPANT_MEMBER_ALREADY_EXISTS': 'Ім\'я представника учасника, яке ви ввели, уже існує в системі.',
  'serverError.description.PARTICIPANT_MEMBER_NOT_FOUND': 'Не вдалось знайти представника учасника, якого ви щукаєте.',
  'serverError.description.PARTICIPANT_NOT_FOUND': 'Не вдалося знайти учасника, якого ви шукаєте.',
  'serverError.description.WRONG_PARTICIPANT_TYPE': 'Тип учасника, якого ви вибрали, невпевнений і не може бути прийнятий.',
  'serverError.description.MARKET_ALREADY_EXISTS': 'Позиція, яку ви намагаєтеся створити, уже існує в системі.',
  'serverError.description.INVALID_TRADING_MODE': 'Режим, який ви вибрали, недійсний.',
  'serverError.description.INVALID_SETTINGS': 'Налаштування, яке ви вибрали для цієї дії є недійсними.',
  'serverError.description.INVALID_CODE': 'Введений вами код недійсний.',
  'serverError.description.INVALID_CATEGORY_TYPE': 'Тип категорії, який ви вибрали недійсний.',
  'serverError.description.MARKET_IS_NOT_IN_LEAGUE': 'Наступна позиція не входить в відповідну лігу.',
  'serverError.description.INVALID_EMAIL': 'Введена вами адреса електронной пошти недійсна.',
  'serverError.description.INVALID_USERNAME': 'Введене вами ім\'я користувача недійсне.',
  'serverError.description.WRONG_USERNAME_PASSWORD': 'Ім\'я користувача і / або пароль, який вы ввели невірні. Будь ласка, спробуйте знову.  ',
  'serverError.description.HASH_IS_NOT_STRING': 'Хеш-функція не працює відповідним чином в рядку.',
  'serverError.description.REQUEST_ALREADY_SENT': 'Ви вже відправили запит.',
  'serverError.description.EXPIRED': 'Час сесії минув.',
  'serverError.description.INVALID_STRING': 'Вибраний рядок недійсний.',
  'serverError.description.DUPLICATE': 'Необхідно додати копію наступного змісту.',
  'serverError.description.INVALID_AMOUNT': 'Введена вами сума недопустима.',
  'serverError.description.INVALID_PERMISSIONS': 'Дозволи, які ви намагаєтеся отримати, є невірними.',
  'serverError.description.EVENT_MISSING_START_DATE': 'Необхідно додати дату початку наступної події.',
  'serverError.description.MORE_THAN_ONE_EVENT_FOUND': 'Було знайдено більше однієї події с тим самим іменем чи даними, які ви ввели.',
  'serverError.description.WRONG_PARTICIPANT': 'Учасник, выбраний вами або введений вами, помилковий чи не існує.',
  'serverError.description.UNKNOWN_TABLE': 'Таблиця, яку ви шукаєте чи ви ввели, невідома.',
  'serverError.description.INVALID_MAPPING': 'Користувач бібліотеки надає недопустиме маппінг значення.',
  'serverError.description.MAPPING_NOT_FOUND': 'Не вдалося знайти необхідний тип маппінга.',
  'serverError.description.LEAGUE_MAPPING_NOT_FOUND': 'Не вдалося знайти необхідний маппінг ліги.',
  'serverError.description.NOT_MAPPED': 'Наступний контент не був відображений.',
  'serverError.description.PARTICIPANT_IS_NOT_IN_LEAGUE': 'Наступний учасник не включений в відповідну лігу.',
  'serverError.description.SELECTION_FIXED_MIN_INVALID': 'Вам не вистачає мінімальної кількості результатів, щоб виконати ваш запит.',
  'serverError.description.SELECTION_FIXED_MAX_INVALID': 'Ви досягли максимальної кількості результатів.',
  'serverError.description.SELECTION_FIXED_MIN_MAX_CONFLICT': 'Сталася помилка між мінімальною і максимальною кількістю результатів. ',
  'serverError.description.INVALID_RULE': 'Певне правило недійсно.',
  'serverError.description.RESULT_NOT_FOUND': 'Результат по вашому запиту не знайдений.',
  'serverError.description.MARKET_COMBINATION_MAX_ERROR': 'Ви досягли максимальної кількості позиційних комбінацій.',
  'serverError.description.MARKET_COMBINATION_MIN_ERROR': 'Вам не вистачає мінімальної кількості позиційних комбінацій для завершення вашого запиту.',
  'serverError.description.MARKET_SETTING_DOES_NOT_EXIST': 'Необхідне налаштування для даної позиції в системі відсутнє.',
  'serverError.description.SPORT_COMBINATION_MAX_ERROR': 'Ви досягли максимальної кількості спортивних комбінацій.',
  'serverError.description.SPORT_COMBINATION_MIN_ERROR': 'Вам не вистачає мінімальної кількості спортивних комбінацій, щоб виконати ваш запит.',
  'serverError.description.COUNTRY_COMBINATION_MAX_ERROR': 'Ви досягли максимальної кількості комбінацій для країни',
  'serverError.description.COUNTRY_COMBINATION_MIN_ERROR': 'Ви досягли мінімальної кількості комбінацій для країни.',
  'serverError.description.LEAGUE_COMBINATION_MAX_ERROR': 'Вам не вистачає мінімальної кількості комбінацій для ліги, щоб виконати ваш запит.',
  'serverError.description.LEAGUE_COMBINATION_MIN_ERROR': 'Ви досягли максимальної кількості комбінацій ліги.',
  'serverError.description.CHANNEL_MISSING': 'Канал відсутній і повинен бути доданий.',
  'serverError.description.WRONG_CHANNEL': 'Канал, який ви вибрали чи ввели, невірний чи не існує.',
  'serverError.description.EVENT_RESTRICTED_BET': 'Тип ставки, який ви вибрали, обмежений для цієї події або наступна подія має обмеження щодо певних типів ставок. ',
  'serverError.description.LEAGUE_RESTRICTED_BET': 'Тип ставки, який ви вибрали, обмежений для цієї ліги або наступна ліга має обмеження щодо певних типів ставок.',
  'serverError.description.COUNTRY_RESTRICTED_BET': 'Тип ставки, який ви вибрали, обмежений для цієї країни.',
  'serverError.description.SPORT_RESTRICTED_BET': 'Тип ставки, який ви вибрали, обмежений для цього виду спорту.',
  'serverError.description.POSSIBLE_WIN_MORE_THAN_OVERASK': 'Сума можливого виграшу перевищує початково визначену суму результату ставки і повинна переходити до перевантаження.',
  'serverError.description.POSSIBLE_WIN_LESS_THAN_OVERASK': 'Сума можливого виграшу менша ніж початково визначена сума результату ставки і повинна переходити до перевантаження. ',
  'serverError.description.BET_IN_REVIEW': 'Ваша ставка розглядається. Ви будете повідомлені про деталі. ',
  'serverError.description.STAKE_MORE_THAN_OVERASK': 'Сума ставки перевищує початково визначену суму результату ставки і повинна переходити до перевантаження.',
  'serverError.description.STAKE_LESS_THAN_OVERASK': 'Сумма ставки менша, ніж почтаково визначена сума результату ставки і повинна переходити до перевантаження.',
  'serverError.description.OVERASK_WRONG_SETTINGS': 'Налаштування, які ви вибрали для перевантаження, невірні.',
  'serverError.description.USER_STAKE_LIMIT_ERROR': 'Ви досягли максимального об\'єму ставки, який ви можете розмістити.',
  'serverError.description.USER_WON_LIMIT_ERROR': 'Ви досягли максимальної суми виграшу, дозволеної на веб-сайті.',
  'serverError.description.BET_WON_LIMIT_ERROR': 'Ви досягли максимальної кількості виграшної ставки.',
  'serverError.description.BET_STAKE_LIMIT_ERROR': 'Ви досягли максимальной суми ставки.',
  'serverError.description.SELECTION_MIXED_MULTIPLES_ERROR': 'При спробі обробити список результатів, доступних для експрес ставки, виникла помилка.',
  'serverError.description.MARKET_MIXED_MULTIPLES_ERROR': 'При спробі обробити список результатів, доступних для експрес ставки на визначеній позиції, виникла помилка.',
  'serverError.description.LEAGUE_MIXED_MULTIPLES_ERROR': 'При спробі обробити список результатів, доступних для експрес ставки в визначеній лізі, виникла помилка.  ',
  'serverError.description.COUNTRY_MIXED_MULTIPLES_ERROR': 'При спробі обробити список результатів, доступних для експрес ставки в визначеній країні, виникла помилка.',
  'serverError.description.SPORT_MIXED_MULTIPLES_ERROR': 'При спробі обробити список результатів, доступних для експрес ставки в визначеному спорті, виникла помилка.  ',
  'serverError.description.BET_LIMIT_WRONG_SETTINGS': 'Налаштування, які ви вибрали для максимальної суми ставки, є неправильними.',
  'serverError.description.INVALID_DYNAMIC_LIMIT': 'Наступний динамічний ліміт є недійсним.',
  'serverError.description.CATEGORY_MAPPING_NOT_FOUND': 'Маппінг категорії не знайдений.',
  'serverError.description.SELECTION_SETTING_DOES_NOT_EXIST': 'Выбраний чи введений параметр результату не існує чи недоступний.',
  'serverError.description.SELECTION_COMBINATION_MIN_ERROR': 'Вам не вистачає мінімальної кількості комбінацій результатів для завершення вашого запиту.',
  'serverError.description.SELECTION_COMBINATION_MAX_ERROR': 'Вы досягли максимальної кількості комбінацій результатів.',
  'serverError.description.INVALID_CURRENCY': 'Введена або вибрана валюта недійсна чи не існує в системі.',
  'serverError.description.EVENT_SELECTION_SETTINGS_NOT_FOUND': 'Параметри, які ви застосували для наступного результату події, не були знайдені.',
  'serverError.description.EVENT_MARKET_SETTINGS_NOT_FOUND': 'Параметри, які ви використали для наступної позиції події, не були знайдені.',
  'serverError.description.INVALID_FIRST_NAME': 'Им\'я, яке ви ввели, недійсне.',
  'serverError.description.INVALID_LAST_NAME': 'Введене вами прізвище недійсне.',
  'serverError.description.INVALID_BIRTHDAY': 'Введений вами день нарождення недійсний.',
  'serverError.description.INVALID_COUNTRY': 'Країна, яку ви ввели або вибрали, недійсна, оскільки ми не надаємо там послуги.',
  'serverError.description.INVALID_ADDRESS': 'Введена вами адреса недійсна.',
  'serverError.description.INVALID_CITY': 'Введене вами місто недійсне.',
  'serverError.description.INVALID_STATE': 'Введенні вами область чи край недійсні.',
  'serverError.description.INVALID_ZIP_CODE': 'Введений вами поштовий індекс недійсний.',
  'serverError.description.INVALID_PHONE': 'Номер телефону, який ви ввели, недійсний.',
  'serverError.description.INVALID_PASSWORD': 'Пароль, який ви ввели, невірний. Він повинен відповідати параметрам, встановленим веб-сайтом (6 символів, без тире, інших символів і т. п.). ',
  'serverError.description.INVALID_ANSWER': 'Введена вами відповідь недійсна.',
  'serverError.description.INVALID_AGE_18': 'Введений вами вік недопустимий. Вам має бути не менше 21, щоб зареєструватися на нашому сайті. ',
  'serverError.description.INVALID_SECRET': 'Введенний секрет недійсний.',
  // I'm here now
  'serverError.description.USER_ALREADY_EXISTS': 'Користувач з тими самим персональними даними уже існує чи користувач з тим самим ім\'ям, електронною поштою і / або іменем користувача уже існує.',
  'serverError.description.PHONE_ALREADY_EXISTS': 'Номер телефону, який ви ввели, уже існує в системі в персональних даних іншого користувача.',
  'serverError.description.USERNAME_ALREADY_EXISTS': 'Ім\'я користувача, яке ви ввели уже використовується іншим користувачем.',
  'serverError.description.EMAIL_ALREADY_EXISTS': 'Введена вами адреса електронної пошти уже зареєстрований іншим користувачем на сайті.',
  'serverError.description.INVALID_QUESTION': 'Питання, яке ви ввели, є недопустимим чи неправильним.',
  'serverError.description.USER_HASH_IS_NOT_FOUND': 'Хеш користувача не знайдений в системі.',
  'serverError.description.USER_HASH_IS_EXPIRED': 'Строк використання, наступного хеша користувача минув.',
  'serverError.description.EVENT_HAS_ACTIVE_BET': 'У наступної події уже є активна ставка.',
  'serverError.description.EVENT_MARKET_HAS_ACTIVE_BET': 'У наступної позиції події уже є активна ставка.',
  'serverError.description.EVENT_SELECTION_HAS_ACTIVE_BET': 'У наступного результату події є активна ставка.',
  'serverError.description.SMS_CODE_IS_INVALID': 'Введенний вами смс-код недійсний.',
  'serverError.description.SMS_CODE_IS_EXPIRED': 'СМС код більше не дійсний, так як він минув.',
  'serverError.description.SMS_CODE_SENT': 'Смс-код був відправлений на ваш номер телефону.',
  'serverError.description.SMS_CODE_IS_OFF': 'Функціональність коду SMS відключена.',
  'serverError.description.EVENT_SETTINGS_DO_NOT_EXIST': 'Вибрані налаштування подій не існують в системі.',
  'serverError.description.MARKET_HAS_ACTIVE_BET': 'У наступної позиції уже є активна ставка.',
  'serverError.description.USER_NOT_VERIFIED': 'Ваш обліковий запис ще не підтверджений або наступний користувач ще не був підтверджений нашим сайтом. ',
  'serverError.description.CURRENCY_NOT_SUPPORTED': 'Вибрана вами валюта не підтримується системою.',
  'serverError.description.TRANSACTION_NOT_FOUND': 'Транзакція, яку ви шукаєте, не знайдена в історії системної статистики.',
  'serverError.description.WRONG_WEBSITE_ID': 'ID веб-сайту, який ви ввели, невірний.',
  'serverError.description.PAYMENT_METHOD_NOT_SUPPORTED_FOR_THIS_WEBSITE': 'Данний спосіб оплати (введений вами спосіб оплати) не підтримується нашим сайтом.',
  'serverError.description.UNKNOWN_FILTER': 'Введений вами фільтр невідомий чи не існує.',
  'serverError.description.INVALID_DOMAIN': 'Введене вами ім\'я домена недійсне чи не існує. Повторіть спробу після перевірки орфографії.',
  'serverError.description.BET_IS_NOT_IN_REVIEW': 'Наступна ставка ще не в процесі розгляду.',
  'serverError.description.INVALID_STATUS': 'Вибраний вами статус недійсний.',
  'serverError.description.SCOPE_OR_STAT_NOT_FOUND': 'Ми не змогли знайти необхідні область використання чи статус.',
  'serverError.description.PAYMENT_NOT_FOUND': 'Спосіб оплати, який ви шукаєте, не знайдений.',
  'serverError.description.WEBSITE_NOT_FOUND': 'Веб-сайт, який ви шукаєте не знайдений. Перевірте назву веб-сайту чи, якщо воно правильно, переконайтеся, що сайт не був видалений назавжди.',
  'serverError.description.PAYMENT_DOES_NOT_SUPPORT_SELECTED_CURRENCY': 'Обрана валюта не підтримується і недоступна для обробки необхідного платежу.',
  'serverError.description.INVALID_IP': 'Ваша IP-адреса недійсна або недопустима IP-адреса.',
  'serverError.description.COMMUNICATION_ERROR': 'При спробі обробити ваш запит сталася помилка зв\'язку.',
  'serverError.description.PURSE_NOT_FOUND': 'гаманець, який ви шукаєте, не знайдений.',
  'serverError.description.BANNER_ID_MISSING': 'ID банера відсутній. Його необхідно додати. ',
  'serverError.description.INVALID_REGISTRATION': 'Процес реєстрації не був успішним і був визнаний недійсним.',
  'serverError.description.INVALID_PAYMENT_DETAILS': 'Введені вами дані про платіж недійсні.',
  'serverError.description.INSUFFICIENT_MERCHANT_FUNDS': 'У вас недостатньо коштів, щоб продовжити запит.',
  'serverError.description.SOME_ELSE_EVENT_AT_THIS_TIME_SELECTED': 'На цей час уже вибрана інша подія.',
  'serverError.description.SESSION_NOT_FOUND': 'Сесія, необхідна для обробки вашого запиту, не знайдена.',
  'serverError.description.CASINO_GAME_NOT_FOUND': 'Казино гра, яку ви шукаєте, не знайдена чи не існує на веб-сайті.',
  'serverError.description.PAYMEGA_API_AUTH_ERROR': 'При спробі обробити ваш запит сталася помилка аутентифікації Paymega API.',
  'serverError.description.PAYMEGA_API_SETTLE_ERROR': 'При спробі обробити ваш запит на Paymega сталася помилка розрахунку API.',
  'serverError.description.TRANSACTION_AUTH_FAILED': 'Системі не вдалося виконати аутентифікацію вашої транзакції. Повторіть спробу, перевіривши персональні та інші важливі дані, які ви вказали.',
  'serverError.description.TRANSACTION_SETTLE_FAILED': 'Системі не вдалося виконати розрахунок вашої транзакції. Повторіть спробу, перевіривши персональні та інші важливі дані, які ви вказали. ',
  'serverError.description.TRANSACTION_CHECK_FAILED': 'Системі не вдалося виконати перевірку вашої транзакції. Повторіть спробу, персональні та інші важливі дані, які ви вказали.',
  'serverError.description.TRANSACTION_VOID_FAILED': 'Системі не вдалося виконати ануляцію вашої транзакції.',
  'serverError.description.UNKNOWN_DOMAIN': 'Ім\'я домену, яке ви ввели, невідомо.',
  'serverError.description.UNKNOWN_EMAIL_TEMPLATE': 'Шаблон електронної пошти, якиц ви шукаєте, невідомий чи не існує.',
  'serverError.description.CASINO_ID_IS_INVALID': 'ID казино, який ви ввели, недійсний чи не існує.',
  'serverError.description.PASSWORD_LENGTH_6': 'Ваш пароль повинен містити не менше 6 символів.',

  'serverError.description.INVALID_TRANSACTION_DETAILS': 'Відомості о транзакції, які ви вказали, є недопустимими. Будь ласка, перевірте їх і повторіть попытку',
  'serverError.description.PHONE_VERIFICATION_FAILED': 'Процедура перевірки вашого номера телефону не вдалася. Ви або вказали неправильний номер телефону, або ввели неправильний код. Будь ласка, спробуйте ще раз',
  'serverError.description.WITHDRAW_MIN_LIMIT': 'Сума, яку ви ввели, менше мінімально допустимої суми виведення',
  'serverError.description.WITHDRAW_MAX_LIMIT': 'Ми не можемо обробити ваш запит, тому що введена вами сума перевищує максимально допустиму суму виведення',
  'serverError.description.DEPOSIT_MAX_LIMIT': 'Ви досягли максимального об\'єму депозиту, який ви можете зробити за один раз. Будь ласка, введіть меншу суму',
  'serverError.description.DEPOSIT_MIN_LIMIT': 'Сума, яку ви ввели, менше дозволеной суми мінімального депозиту',
  'serverError.description.REGISTRATION_EMAIL_SEND_BUT_NOT_VERIFIED': 'Электронна пошта реєстрації вже відправлена вам, але ви ще не підтвердили її',
  'serverError.description.ACTIVE_BETS_ON_EVENT': 'Мы не можемо обробити ваш запит, тому що на цій події все ще активні ставки',
  'serverError.description.VERIFIED_DOCUMENT_CANNOT_BE_DELETED': 'Цей документ був підтверджений веб-сайтом і не може бути видалений',
  'serverError.description.FIELD_IS_BLOCKED_TO_EDIT': 'Ви не можете редагувати наступне поле, тому що воно було заблоковано',
  'serverError.description.INVALID_SOCIAL_ID': 'ID введений для наступного соціального сайту, недейсний',

  'serverError.description.EVENT_MARKET_MAX_WINNERS': 'Ваш запит не може бути оброблений, тому що на наступній позиції події максимальна кількість переможців',
  'serverError.description.DOCUMENT_WAS_DELETED_BY_USER': 'Документ, який ви намагаєтеся відкрити, був видалений користувачем',
  'serverError.description.AGE_FROM_IS_NOT_NUMBER': 'Початковий вік може бути введений лише в цифрах',
  'serverError.description.AGE_FROM_IS_LESS_THAN_18': 'Початковий вік повинен бути 18 в вище. Вік, який ви ввели, нижче 18',
  'serverError.description.AGE_TO_IS_NOT_NUMBER': 'Поле введення максимального віку може бути заповнено тільки цифрами',
  'serverError.description.AGE_TO_IS_NOT_BETWEEN_18_AND_100': 'Максимальний вік повинен бути чимось між 18 і 100. Вік, який ви ввели, не відповідають цій шкалі',
  'serverError.description.AGE_TO_IS_LESS_THAN_AGE_FROM': 'Максимальний вік не може бути менше, ніж початковий вік, будь ласка, перевірте свої дані',
  'serverError.description.INVALID_DATE': 'Дата, вказана вами, недійсна, повторіть спробу',
}