export default {
  'serverSuccess.title.202': 'Accepted',
  'serverSuccess.title.201': 'Created',
  'serverSuccess.title.100': 'Continue',
  'serverSuccess.title.204': 'No Content',
  'serverSuccess.title.200': 'OK',
  'serverSuccess.title.206': 'Partial Content',
  'serverSuccess.title.205': 'Reset Content',
  'serverSuccess.title.203': 'Non-Authoritative Information',

  'serverSuccess.description.202': 'Your request was received but the processing is not complete yet',
  'serverSuccess.description.201': 'Your request has been successfully fulfilled and the resource has been created',
  'serverSuccess.description.100': 'The process is successfully in action, you can continue with the request or ignore it if it is already done',
  'serverSuccess.description.204': 'The server has successfully fulfilled your request. There is no additional content to send in the response payload body',
  'serverSuccess.description.200': 'Your request was technically OK and the server was able to respond and process it properly',
  'serverSuccess.description.206': 'Partial Content',
  'serverSuccess.description.205': 'The request has been successfully completed. Please, reset the ‘document view’ to its original and initial state in which it was received from the origin server',
  'serverSuccess.description.203': 'Non-Authoritative Information',

  'serverInfo.title.300': 'Multiple Choices',
  'serverInfo.title.305': 'Use Proxy',

  'serverError.title.502': 'Bad Gateway',
  'serverError.title.400': 'Bad Request',
  'serverError.title.409': 'Conflict',
  'serverError.title.417': 'Expectation Failed',
  'serverError.title.424': 'Failed Dependency',
  'serverError.title.403': 'Forbidden',
  'serverError.title.504': 'Gateway Timeout',
  'serverError.title.410': 'Gone',
  'serverError.title.505': 'HTTP Version Not Supported',
  'serverError.title.418': 'I\'m Teapot',
  'serverError.title.419': 'Insufficient Space On Resource',
  'serverError.title.507': 'Insufficient Storage',
  'serverError.title.500': 'Internal Server Error',
  'serverError.title.411': 'Length Required',
  'serverError.title.423': 'Locked',
  'serverError.title.420': 'Method Failure',
  'serverError.title.405': 'Method Not Allowed',
  'serverError.title.301': 'Moved Permanently',
  'serverError.title.302': 'Moved Temporarily',
  'serverError.title.207': 'Multi-Status',
  'serverError.title.300': 'Multiple Choices',
  'serverError.title.511': 'Network Authentication Required',
  'serverError.title.406': 'Not Acceptable',
  'serverError.title.404': 'Not Found',
  'serverError.title.501': 'Not Implemented',
  'serverError.title.402': 'Payment Required',
  'serverError.title.308': 'Permanent Redirect',
  'serverError.title.412': 'Precondition Failed',
  'serverError.title.428': 'Precondition Required',
  'serverError.title.407': 'Proxy Authentication Required',
  'serverError.title.431': 'Request Header Fields Too Large',
  'serverError.title.408': 'Request Timeout',
  'serverError.title.413': 'Request Too Long',
  'serverError.title.414': 'Request URI Too Long',
  'serverError.title.416': 'Requested Range Not Satisfiable',
  'serverError.title.503': 'Service Unavailable',
  'serverError.title.101': 'Switching Protocols',
  'serverError.title.429': 'Too Many Requests',
  'serverError.title.UNAUTHORIZED': 'Unauthorized',
  'serverError.title.422': 'Unprocessable Entity',
  'serverError.title.415': 'Unsupported Media Type',
  'serverError.title.917': 'Category Doesn\'t Exists',

  'serverError.title.CATEGORY_ALREADY_EXISTS': 'Category Already Exists',
  'serverError.title.MARKET_DOES_NOT_EXISTS': 'Market Does Not Exist',
  'serverError.title.NO_SUCH_CODE': 'No Such Code',
  'serverError.title.EVENT_DOES_NOT_EXIST': 'Event Does Not Exist',
  'serverError.title.INCORRECT_MARKET_CODE': 'Incorrect Market Code',
  'serverError.title.NOT_SUPPORTED_EVENT_TYPE': 'Not Supported Event Type',
  'serverError.title.INCORRECT_SELECTION': 'Incorrect Selection',
  'serverError.title.FOUND_MORE_THAN_ONE_EVENT': 'Found More Than One Event',
  'serverError.title.EVENT_NOT_FOUND': 'Event Not Found',
  'serverError.title.PARTICIPANT_NOT_MAPPED': 'Participant Not Found',
  'serverError.title.SPORT_NOT_MAPPED': 'Sport Not Mapped',
  'serverError.title.COUNTRY_NOT_MAPPED': 'Country Not Mapped',
  'serverError.title.LEAGUE_NOT_MAPPED': 'League Not Mapped',
  'serverError.title.INCORRECT_SELECTION_TYPE': 'Incorrect Selection Type',
  'serverError.title.MARKET_ID_IS_MISSING': 'Market ID Is Missing',
  'serverError.title.MAP_ID_IS_MISSING': 'Map ID Is Missing',
  'serverError.title.QUERY_ERROR': 'Query Error',
  'serverError.title.SELECTIONS_MAPPINGS_MISSING': 'Selections Mappings Missing',
  'serverError.title.SELECTION_MAP_ID_IS_MISSING': 'Selections Map ID Is Missing',
  'serverError.title.SELECTION_SYSTEM_ID_IS_MISSING': 'Selections System ID Is Missing',
  'serverError.title.PROVIDER_SYSTEM_ID_IS_MISSING': 'Provider ID Is Missing',
  'serverError.title.MARKET_MAPPINGS_MISSING': 'Market Mappings Missing',
  'serverError.title.MARKET_NOT_MAPPED': 'Market Not Mapped',
  'serverError.title.MARKET_NOT_FOUND': 'Market Not Found',
  'serverError.title.EVENT_NOT_MAPPED': 'Event Not Mapped',
  'serverError.title.SELECTION_NOT_MAPPED': 'Selection Not Mapped',
  'serverError.title.EVENT_MARKET_NOT_MAPPED': 'Event Market Not Mapped',
  'serverError.title.UNKNOWN_PROVIDER': 'Unknown Provider',
  'serverError.title.PARTICIPANT_ID_MISSING': 'Participant ID Is Missing',
  'serverError.title.INVALID_USER_ID': 'Invalid User Id',
  'serverError.title.WRONG_ENTITY': 'Wrong Entity',
  'serverError.title.USER_ID_MISSING': 'User ID Missing',
  'serverError.title.USER_NOT_FOUND': 'Wrong Entity',
  'serverError.title.SELECTION_DOES_NOT_EXIST': 'Selection Does Not Exist',
  'serverError.title.EVENT_MARKET_NOT_FOUND': 'Event Market Not Found',
  'serverError.title.EVENT_SELECTION_NOT_FOUND': 'Event Selection Not Found',
  'serverError.title.INCORRECT_AMOUNT': 'Incorrect Amount',
  'serverError.title.ACCESS_DENIED': 'Access Denied',
  'serverError.title.EVENT_IS_NOT_ACTIVE': 'Event Is Not Active',
  'serverError.title.EVENT_MARKET_IS_NOT_ACTIVE': 'Event Market Is Not Active',
  'serverError.title.EVENT_SELECTION_IS_NOT_ACTIVE': 'Event Selection Is Not Active',
  'serverError.title.MARKET_IS_NOT_ACTIVE': 'Market Is Not Active',
  'serverError.title.SPORT_IS_NOT_ACTIVE': 'Sport Is Not Active',
  'serverError.title.COUNTRY_IS_NOT_ACTIVE': 'Country Is Not Active',
  'serverError.title.LEAGUE_IS_NOT_ACTIVE': 'League Is Not Active',
  'serverError.title.EVENT_SELECTION_ODD_RESTRICTION': 'Event Selection Odd Restriction',
  'serverError.title.COMBINATION_GROUP_RESTRICTION': 'Combination Group Restriction',
  'serverError.title.BAD_QUERY': 'Bad Query',
  'serverError.title.CATEGORY_NOT_FOUND': 'Category Not Found',
  'serverError.title.UPDATE_DEFAULT_MARKET': 'Update Default Market',
  'serverError.title.CATEGORY_NOT_ACTIVE': 'Category Not Active',
  'serverError.title.INACTIVE_USER': 'Inactive User',
  'serverError.title.INSUFFICIENT_BALANCE': 'Insufficient Balance',
  'serverError.title.INVALID_BET_TYPE': 'Invalid Bet Type',
  'serverError.title.INVALID_BET_DETAILS': 'Invalid Bet Details',
  'serverError.title.INVALID_STAKE': 'Invalid Stake',
  'serverError.title.EMAIL_TEMPLATE_NOT_FOUND': 'Email Template Not Found',
  'serverError.title.EMAIL_NOT_FOUND': 'Email Not Found',
  'serverError.title.BLOCKED_USER': 'Blocked User',
  'serverError.title.MARKET_IS_NOT_READY_FOR_BETS': 'Market Is Not Ready For Bets',
  'serverError.title.EVENT_HISTORY_ID_DOES_NOT_EXIST': 'Event History ID Does Not Exist',
  'serverError.title.INVALID_CATEGORY_ID': 'Invalid Category ID',
  'serverError.title.INVALID_LEAGUE_ID': 'Invalid League ID',
  'serverError.title.LEAGUE_TYPE_NOT_FOUND': 'League Type Not Found',
  'serverError.title.MARKET_SELECTION_ALREADY_EXISTS': 'Market Selection Already Exists',
  'serverError.title.PARTICIPANT_MEMBER_ID_MISSING': 'Participant Member ID Missing',
  'serverError.title.PARTICIPANT_MEMBER_NOT_FOUND': 'Participant Member Not Found',
  'serverError.title.PARTICIPANT_NOT_FOUND': 'Participant Not Found',
  'serverError.title.WRONG_PARTICIPANT_TYPE': 'Wrong Participant Type',
  'serverError.title.MARKET_ALREADY_EXISTS': 'Market Already Exists',
  'serverError.title.INVALID_TRADING_MODE': 'Invalid Trading Mode',
  'serverError.title.INVALID_SETTINGS': 'Invalid Settings',
  'serverError.title.INVALID_CODE': 'Invalid Code',
  'serverError.title.INVALID_CATEGORY_TYPE': 'Invalid Category Type',
  'serverError.title.MARKET_IS_NOT_IN_LEAGUE': 'Market Is Not In League',
  'serverError.title.INVALID_EMAIL': 'Invalid Email',
  'serverError.title.INVALID_USERNAME': 'Invalid Username',
  'serverError.title.WRONG_USERNAME_PASSWORD': 'Wrong Username Or Password',
  'serverError.title.HASH_IS_NOT_STRING': 'Hash Is Not String',
  'serverError.title.REQUEST_ALREADY_SENT': 'Request Already Sent',
  'serverError.title.EXPIRED': 'Expired',
  'serverError.title.INVALID_STRING': 'Invalid String',
  'serverError.title.DUPLICATE': 'Duplicate',
  'serverError.title.INVALID_AMOUNT': 'Invalid Amount',
  'serverError.title.INVALID_PERMISSIONS': 'Invalid Permissions',
  'serverError.title.EVENT_MISSING_START_DATE': 'Event Missing Start Date',
  'serverError.title.MORE_THAN_ONE_EVENT_FOUND': 'More Than One Event Found',
  'serverError.title.WRONG_PARTICIPANT': 'Wrong Participant',
  'serverError.title.UNKNOWN_TABLE': 'Unknown Table',
  'serverError.title.INVALID_MAPPING': 'Invalid Mapping',
  'serverError.title.MAPPING_NOT_FOUND': 'Mapping Not Found',
  'serverError.title.LEAGUE_MAPPING_NOT_FOUND': 'League Mapping Not Found',
  'serverError.title.NOT_MAPPED': 'Not Mapped',
  'serverError.title.PARTICIPANT_IS_NOT_IN_LEAGUE': 'Participant Is Not In League',
  'serverError.title.SELECTION_FIXED_MIN_INVALID': 'Selection Fixed Min Invalid',
  'serverError.title.SELECTION_FIXED_MAX_INVALID': 'Selection Fixed Max Invalid',
  'serverError.title.SELECTION_FIXED_MIN_MAX_CONFLICT': 'Selection Fixed Min Max Conflict',
  'serverError.title.INVALID_RULE': 'Invalid Rule',
  'serverError.title.RESULT_NOT_FOUND': 'Result Not Found',
  'serverError.title.MARKET_COMBINATION_MAX_ERROR': 'Market Combination Max Error',
  'serverError.title.MARKET_COMBINATION_MIN_ERROR': 'Market Combination Min Error',
  'serverError.title.MARKET_SETTING_DOES_NOT_EXIST': 'Market Setting Does Not Exist',
  'serverError.title.SPORT_COMBINATION_MAX_ERROR': 'Sport Combination Max Error',
  'serverError.title.SPORT_COMBINATION_MIN_ERROR': 'Sport Combination Min Error',
  'serverError.title.COUNTRY_COMBINATION_MAX_ERROR': 'Country Combination Max Error',
  'serverError.title.COUNTRY_COMBINATION_MIN_ERROR': 'Country Combination Min Error',
  'serverError.title.LEAGUE_COMBINATION_MAX_ERROR': 'League Combination Max Error',
  'serverError.title.LEAGUE_COMBINATION_MIN_ERROR': 'League Combination Min Error',
  'serverError.title.CHANNEL_MISSING': 'Channel Missing',
  'serverError.title.WRONG_CHANNEL': 'Wrong Channel',
  'serverError.title.EVENT_RESTRICTED_BET': 'Event Restricted Bet',
  'serverError.title.LEAGUE_RESTRICTED_BET': 'League Restricted Bet',
  'serverError.title.COUNTRY_RESTRICTED_BET': 'Country Restricted Bet',
  'serverError.title.SPORT_RESTRICTED_BET': 'Sport Restricted Bet',
  'serverError.title.POSSIBLE_WIN_MORE_THAN_OVERASK': 'Possible Win More Than Overask',
  'serverError.title.POSSIBLE_WIN_LESS_THAN_OVERASK': 'Possible Win Less Than Overask',
  'serverError.title.BET_IN_REVIEW': 'Bet In Review',
  'serverError.title.STAKE_MORE_THAN_OVERASK': 'Stake More Than Overask',
  'serverError.title.STAKE_LESS_THAN_OVERASK': 'Stake Less Than Overask',
  'serverError.title.OVERASK_WRONG_SETTINGS': 'Overask Wrong Settings',
  'serverError.title.USER_STAKE_LIMIT_ERROR': 'User Stake Limit Error',
  'serverError.title.USER_WON_LIMIT_ERROR': 'User Won Limit Error',
  'serverError.title.BET_WON_LIMIT_ERROR': 'Bet Won Limit Error',
  'serverError.title.BET_STAKE_LIMIT_ERROR': 'Bet Stake Limit Error',
  'serverError.title.SELECTION_MIXED_MULTIPLES_ERROR': 'Selection Mixed Multiple Error',
  'serverError.title.MARKET_MIXED_MULTIPLES_ERROR': 'Market Mixed Multiple Error',
  'serverError.title.LEAGUE_MIXED_MULTIPLES_ERROR': 'League Mixed Multiple Error',
  'serverError.title.COUNTRY_MIXED_MULTIPLES_ERROR': 'Country Mixed Multiple Error',
  'serverError.title.SPORT_MIXED_MULTIPLES_ERROR': 'Sport Mixed Multiple Error',
  'serverError.title.BET_LIMIT_WRONG_SETTINGS': 'Bet Mixed Multiple Error',
  'serverError.title.INVALID_DYNAMIC_LIMIT': 'Invalid Dynamic Limit',
  'serverError.title.CATEGORY_MAPPING_NOT_FOUND': 'Category Mapping Not Found',
  'serverError.title.SELECTION_SETTING_DOES_NOT_EXIST': 'Selection Setting Does Not Exist',
  'serverError.title.SELECTION_COMBINATION_MIN_ERROR': 'Selection Combination Min Error',
  'serverError.title.SELECTION_COMBINATION_MAX_ERROR': 'Selection Combination Max Error',
  'serverError.title.INVALID_CURRENCY': 'Invalid Currency',
  'serverError.title.EVENT_SELECTION_SETTINGS_NOT_FOUND': 'Event Selection Settings Not Found',
  'serverError.title.EVENT_MARKET_SETTINGS_NOT_FOUND': 'Event Market Settings Not Found',
  'serverError.title.INVALID_FIRST_NAME': 'Invalid First Name',
  'serverError.title.INVALID_LAST_NAME': 'Invalid Last Name',
  'serverError.title.INVALID_BIRTHDAY': 'Invalid Birthday',
  'serverError.title.INVALID_COUNTRY': 'Invalid Country',
  'serverError.title.INVALID_ADDRESS': 'Invalid Address',
  'serverError.title.INVALID_CITY': 'Invalid City',
  'serverError.title.INVALID_STATE': 'Invalid State',
  'serverError.title.INVALID_ZIP_CODE': 'Invalid Zip Code',
  'serverError.title.INVALID_PHONE': 'Invalid Phone',
  'serverError.title.INVALID_PASSWORD': 'Invalid Password',
  'serverError.title.INVALID_ANSWER': 'Invalid Answer',
  'serverError.title.INVALID_AGE_18': 'Invalid Age 18',
  'serverError.title.INVALID_SECRET': 'Invalid Secret',
  'serverError.title.USER_ALREADY_EXISTS': 'User Already Exists',
  'serverError.title.PHONE_ALREADY_EXISTS': 'Phone Already Exists',
  'serverError.title.USERNAME_ALREADY_EXISTS': 'Username Already Exists',
  'serverError.title.EMAIL_ALREADY_EXISTS': 'Email Already Exists',
  'serverError.title.INVALID_QUESTION': 'Invalid Question',
  'serverError.title.USER_HASH_IS_NOT_FOUND': 'User Hash Is Not Found',
  'serverError.title.USER_HASH_IS_EXPIRED': 'User Hash Is Expired',
  'serverError.title.EVENT_HAS_ACTIVE_BET': 'Event Has Active Bet',
  'serverError.title.EVENT_MARKET_HAS_ACTIVE_BET': 'Event Market Has Active Bet',
  'serverError.title.EVENT_SELECTION_HAS_ACTIVE_BET': 'Event Selection Has Active Bet',
  'serverError.title.SMS_CODE_IS_INVALID': 'SMS Code Is Invalid',
  'serverError.title.SMS_CODE_IS_EXPIRED': 'SMS Code Is Expired',
  'serverError.title.SMS_CODE_SENT': 'SMS Code Send',
  'serverError.title.SMS_CODE_IS_OFF': 'SMS Code Is Off',
  'serverError.title.EVENT_SETTINGS_DO_NOT_EXIST': 'Event Settings Do Not Exist',
  'serverError.title.MARKET_HAS_ACTIVE_BET': 'Market Has Active Bet',
  'serverError.title.USER_NOT_VERIFIED': 'User Not Verified',
  'serverError.title.CURRENCY_NOT_SUPPORTED': 'Currency Not Supported',
  'serverError.title.TRANSACTION_NOT_FOUND': 'Transaction Not Found',
  'serverError.title.WRONG_WEBSITE_ID': 'Wrong Website ID',
  'serverError.title.PAYMENT_METHOD_NOT_SUPPORTED_FOR_THIS_WEBSITE': 'Payment Method Not Supported For This Website',
  'serverError.title.UNKNOWN_FILTER': 'Unknown Filter',
  'serverError.title.INVALID_DOMAIN': 'Invalid Domain',
  'serverError.title.BET_IS_NOT_IN_REVIEW': 'Bet Is Not In Review',
  'serverError.title.INVALID_STATUS': 'Invalid Status',
  'serverError.title.SCOPE_OR_STAT_NOT_FOUND': 'Scope Or Stat Not Found',
  'serverError.title.PAYMENT_NOT_FOUND': 'Payment Not Found',
  'serverError.title.WEBSITE_NOT_FOUND': 'Website Not Found',
  'serverError.title.PAYMENT_DOES_NOT_SUPPORT_SELECTED_CURRENCY': 'Payment Does Not Support Selected Currency',
  'serverError.title.INVALID_IP': 'Invalid IP',
  'serverError.title.COMMUNICATION_ERROR': 'Communication Error',
  'serverError.title.PURSE_NOT_FOUND': 'Purse Not Found',
  'serverError.title.BANNER_ID_MISSING': 'Banner\'s ID Missing',
  'serverError.title.INVALID_REGISTRATION': 'Invalid Registration',
  'serverError.title.INVALID_PAYMENT_DETAILS': 'Invalid Payment Details',
  'serverError.title.INSUFFICIENT_MERCHANT_FUNDS': 'Insufficient Merchant Funds',
  'serverError.title.SOME_ELSE_EVENT_AT_THIS_TIME_SELECTED': 'Some Else Event At This Time Selected',
  'serverError.title.SESSION_NOT_FOUND': 'Session Not Found',
  'serverError.title.CASINO_GAME_NOT_FOUND': 'Casino Game Not Found',
  'serverError.title.PAYMEGA_API_AUTH_ERROR': 'Paymega Api Auth Error',
  'serverError.title.PAYMEGA_API_SETTLE_ERROR': 'Paymega Api Settle Error',
  'serverError.title.TRANSACTION_AUTH_FAILED': 'Transaction Auth Failed',
  'serverError.title.TRANSACTION_SETTLE_FAILED': 'Transaction Settle Failed',
  'serverError.title.TRANSACTION_CHECK_FAILED': 'Transaction Check Failed',
  'serverError.title.TRANSACTION_VOID_FAILED': 'Transaction Void Failed',
  'serverError.title.UNKNOWN_DOMAIN': 'Unknown Domain',
  'serverError.title.UNKNOWN_EMAIL_TEMPLATE': 'Unknown Email Template',
  'serverError.title.CASINO_ID_IS_INVALID': 'Casino ID Is Invalid',
  'serverError.title.PASSWORD_LENGTH_6': 'Password Length 6',
  'serverError.title.INVALID_TRANSACTION_DETAILS': 'Invalid Transaction Details',
  'serverError.title.PHONE_VERIFICATION_FAILED': 'Phone Verification Failed',
  'serverError.title.WITHDRAW_MIN_LIMIT': 'Withdraw Min Limit',
  'serverError.title.WITHDRAW_MAX_LIMIT': 'Withdraw Max Limit',
  'serverError.title.DEPOSIT_MIN_LIMIT': 'Deposit Min Limit',
  'serverError.title.DEPOSIT_MAX_LIMIT': 'Deposit Max Limit',
  'serverError.title.REGISTRATION_EMAIL_SEND_BUT_NOT_VERIFIED': 'Registration Email Send But Not Verified',
  'serverError.title.ACTIVE_BETS_ON_EVENT': 'Active Bets On Event',
  'serverError.title.VERIFIED_DOCUMENT_CANNOT_BE_DELETED': 'Verified Document Cannot Be Deleted',
  'serverError.title.FIELD_IS_BLOCKED_TO_EDIT': 'Field Is Blocked To Edit',
  'serverError.title.INVALID_SOCIAL_ID': 'Invalid Social ID',

  'serverError.title.EVENT_MARKET_MAX_WINNERS': 'Event Market Max Winners',
  'serverError.title.DOCUMENT_WAS_DELETED_BY_USER': 'Document Was Deleted By User',
  'serverError.title.AGE_FROM_IS_NOT_NUMBER': 'Age From Is Not Number',
  'serverError.title.AGE_FROM_IS_LESS_THAN_18': 'Age From Is Less Than 18',
  'serverError.title.AGE_TO_IS_NOT_NUMBER': 'Age To Is Not Number',
  'serverError.title.AGE_TO_IS_NOT_BETWEEN_18_AND_100': 'Age To Is Not Between 18 And 100',
  'serverError.title.AGE_TO_IS_LESS_THAN_AGE_FROM': 'Age To Is Less Than Age From',
  'serverError.title.INVALID_DATE': 'Invalid Date',


  'serverError.description.502': 'Server error: Your request could not be completed as the proxy server stumbled upon a temporary error',
  'serverError.description.400': 'Your browser sent a request which the server could not understand. The size of the request header field exceeds server limit',
  'serverError.description.409': 'Your request had an invalid session-ID header. Please, try again later or contact your system administrator',
  'serverError.description.417': 'The expectation given in the Expect request-header could not be carried out by the current server',
  'serverError.description.424': 'Your request could not be processed as a result of a failure of a previous request. Please, try again!',
  'serverError.description.403': 'You don’t have permission to access on the current server',
  'serverError.description.504': 'A GATEWAY TIMEOUT error occurred as a result of which the server is out of reach. Please, retry the request!',
  'serverError.description.410': `Page deleted or gone. The source you requested is not available on this server and we lack a forwarding address.
                                  This might be because of several reasons: 
                                    <ul>
                                        <li>The web address you entered is incorrect, or </li>
                                        <li>The page you are looking for has been permanently deleted.</li>
                                    </ul>
                                 `,
  'serverError.description.505': 'The HTTP version used in your request is invalid or is not supported by our server. Please, try again!',
  'serverError.description.418': 'The requested entity body is short and stout. Tip me over and pour me out. Your request for coffee was rejected as our server is a teapot',
  'serverError.description.419': 'An unexpected error has occurred which implies that there is insufficient disk space for carrying out the operation. Check the server log for more details',
  'serverError.description.507': 'The server is unable to store the representation required to carry out and complete your request',
  'serverError.description.500': 'The server stumbled upon an internal error or misconfiguration due to which the completion of your request was interrupted. Please, contact the server administrator for solving the issue',
  'serverError.description.411': 'The server rejects to accept your request without a defined Content- Length. You can try sending the request again if a valid Content-Length header field with the corresponding message-body in the request message is added',
  'serverError.description.423': 'The source or destination resource of a method is locked',
  'serverError.description.420': 'A system error occurred. The reason for this might be the files damage of your windows system. Please, try sending your request again or contact a server administrator',
  'serverError.description.405': 'The method mentioned in the Request-Line is not permitted for the resource identified by the Request-URI',
  'serverError.description.301': 'The resource you have requested for has been assigned to a new permanent URI hence any further references to the resource should use the following URI',
  'serverError.description.302': 'There was an error while contacting the server. The resource you have requested for is under a different temporary URI. Please, continue using the Request-URI for future requests, as the redirection might be changed on occasion',
  'serverError.description.207': 'An error occurred while trying to process your request. It seems that multiple operations took place, and you can find the status for each operation in the body of the response',
  'serverError.description.511': 'You need to go through the process of authentication in order to gain access to the network',
  'serverError.description.406': 'Your request is not acceptable. An appropriate representation of the requested resource could not be found on this server',
  'serverError.description.404': 'An error occurred while trying to process your request. The server could not find what you requested for',
  'serverError.description.501': 'A server error occurred while processing your request. The server either does not recognize the method of your request or it does not have the functionality of fulfilling it',
  'serverError.description.402': 'The server stumbled upon an internal error or misconfiguration and was not able to process your request. Please, contact the server administrator and inform them about the time of the error as well as about the action you took before it happened. The server error log might also give you more information regarding the matter',
  'serverError.description.412': 'Your request could not be processed because of the preconditions set in the request header. These preconditions prevent the requested method from being applied to a resource other than the one intended',
  'serverError.description.308': 'The requested page has been permanently moved',
  'serverError.description.407': 'The server is unable to complete the request because you lack the needed authentication credentials for a proxy server',
  'serverError.description.428': 'The server requires that your request is conditional. In other words, the required precondition header, such as If-Match, is missing',
  'serverError.description.431': 'The server is unwilling to process your request because its header fields are too large. If the size of the request header fields is reduced, the request may be resubmitted and processed to completion',
  'serverError.description.408': 'Your browser failed to send a complete request in time hence the request got timed out by the server. Please, contact the server administrator to lengthen the “Connection Timeout” process if you think your request should not have been timed out',
  'serverError.description.413': 'An error occurred when trying to process your request. The requested source does not allow request data with POST requests, or the amount of data provided in the request is beyond the capacity limit',
  'serverError.description.414': `An error occurred when trying to process your request. The requested source does not allow request data with POST requests, or the amount of data provided in the request is beyond the capacity limit' +
                                    <ul>
                                        <li>The URI you want to access to, is too long for the server to be able to interpret. This might have happened because of a number of reasons:</li>
                                        <li>Descending into a loop of redirection</li>
                                        <li>Attempt to exploit potential security holes</li>
                                    </ul>`,
  'serverError.description.416': 'The requested ranges cannot be served by the server because, either your document does not contain the given ranges or the Range header value is not compatible with any meaningful valueThe requested ranges cannot be served by the server because, either your document does not contain the given ranges or the Range header value is not compatible with any meaningful value',
  'serverError.description.503': 'The service is temporarily unable to process your request because of maintenance downtime or capacity related problems. Please, try again later',
  'serverError.description.101': 'The protocol you requested for is being switched to by the server. A message, including the Upgrade request header, was sent',
  'serverError.description.429': 'Your IP address has come up with too many requests to the current service over a short amount of time. Please, try again later. \n If you happen to be behind a proxy or coming from a large company, you might be the same person as many other users. Please, contact the server administrator in that case',
  'serverError.description.UNAUTHORIZED': 'As a result of invalid credentials, access to the page or directory you requested for is denied',
  'serverError.description.422': 'The change you requested could not be processed and was rejected',
  'serverError.description.415': 'Your request was rejected due to the resource being in a format that is not supported by the server',
  'serverError.description.917': 'An error occurred when trying to process your request. Please, try again later or contact the server administrator for further instructions',

  'serverError.description.CATEGORY_ALREADY_EXISTS': 'A category with the same name already exists.',
  'serverError.description.MARKET_DOES_NOT_EXISTS': 'The market you are looking for does not exist.',
  'serverError.description.NO_SUCH_CODE': 'We could not find a matching response to the code you have inserted.',
  'serverError.description.EVENT_DOES_NOT_EXIST': 'The event you are looking for does not exist',
  'serverError.description.INCORRECT_MARKET_CODE': 'The market code you have entered is incorrect',
  'serverError.description.NOT_SUPPORTED_EVENT_TYPE': 'The event type you are creating or choosing is not supported by the system',
  'serverError.description.INCORRECT_SELECTION': 'The selection name you have entered is incorrect',
  'serverError.description.FOUND_MORE_THAN_ONE_EVENT': 'We found more than one event corresponding to your request',
  'serverError.description.EVENT_NOT_FOUND': 'The event you are looking for could not be found',
  'serverError.description.PARTICIPANT_NOT_MAPPED': 'The participant is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.SPORT_NOT_MAPPED': 'The sport is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.COUNTRY_NOT_MAPPED': 'The country is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.LEAGUE_NOT_MAPPED': 'The league is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.INCORRECT_SELECTION_TYPE': 'You have entered an incorrect type of selection',
  'serverError.description.MARKET_ID_IS_MISSING': 'You have not determined the Market ID',
  'serverError.description.MAP_ID_IS_MISSING': 'You have not determined the Map ID',
  'serverError.description.QUERY_ERROR': 'A query error occurred while trying to process your request',
  'serverError.description.SELECTIONS_MAPPINGS_MISSING': 'The mappings for selections are missing and need to be added.',
  'serverError.description.SELECTION_MAP_ID_IS_MISSING': 'You have not determined the Selection Map ID',
  'serverError.description.SELECTION_SYSTEM_ID_IS_MISSING': 'You have not determined the Selection System ID',
  'serverError.description.PROVIDER_SYSTEM_ID_IS_MISSING': 'You have not determined the Provider ID',
  'serverError.description.MARKET_MAPPINGS_MISSING': 'The mappings for markets are missing and need to be added',
  'serverError.description.MARKET_NOT_MAPPED': 'The market is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.MARKET_NOT_FOUND': 'The market you are looking for could not be found',
  'serverError.description.EVENT_NOT_MAPPED': 'The event is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.SELECTION_NOT_MAPPED': 'The selection is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.EVENT_MARKET_NOT_MAPPED': 'The event market is not mapped and added to the corresponding position because of the lack of respective resources',
  'serverError.description.UNKNOWN_PROVIDER': 'The provider you have chosen is unknown to the system',
  'serverError.description.PARTICIPANT_ID_MISSING': 'The ID of the participant is missing and needs to be added',
  'serverError.description.INVALID_USER_ID': 'The User ID you have chose are looking for is invalid already exists on the system/could not be found',
  'serverError.description.WRONG_ENTITY': 'The entity you have entered is wrong or is not available. The entity you have chosen does not comply with the system’s list of entities and/or regulations',
  'serverError.description.USER_ID_MISSING': 'The User ID needs to be added as it has not been determined yet and is missing',
  'serverError.description.USER_NOT_FOUND': 'The user you are looking for could not be found',
  'serverError.description.SELECTION_DOES_NOT_EXIST': 'The selection you are searching for does not exist on the system',
  'serverError.description.EVENT_MARKET_NOT_FOUND': 'The event market you are looking for could not be found',
  'serverError.description.EVENT_SELECTION_NOT_FOUND': 'The event selection you are searching, could not be found',
  'serverError.description.INCORRECT_AMOUNT': 'The amount you have entered is incorrect',
  'serverError.description.ACCESS_DENIED': 'We are sorry to inform that you cannot access to the following data, section or information',
  'serverError.description.EVENT_IS_NOT_ACTIVE': 'The event you are trying to open is no longer active',
  'serverError.description.EVENT_MARKET_IS_NOT_ACTIVE': 'The event market you are trying to access is no longer active',
  'serverError.description.EVENT_SELECTION_IS_NOT_ACTIVE': 'The event selection you are trying to access is no longer active',
  'serverError.description.MARKET_IS_NOT_ACTIVE': 'The market you are trying to access is no longer active',
  'serverError.description.SPORT_IS_NOT_ACTIVE': 'The following sport type is no longer active',
  'serverError.description.COUNTRY_IS_NOT_ACTIVE': 'The country you want to enter or choose is not active',
  'serverError.description.LEAGUE_IS_NOT_ACTIVE': 'The league you want to access is no longer active',
  'serverError.description.EVENT_SELECTION_ODD_RESTRICTION': 'You have reached the highest point of odd restrictions on event selections',
  'serverError.description.COMBINATION_GROUP_RESTRICTION': 'You have reached the maximum amount of combination groups',
  'serverError.description.BAD_QUERY': 'There was an error while trying to process your request. Please, try again in the correct way',
  'serverError.description.CATEGORY_NOT_FOUND': 'The category you are looking for could not be found',
  'serverError.description.UPDATE_DEFAULT_MARKET': 'Please, update the default market by changing it into a new one',
  'serverError.description.CATEGORY_NOT_ACTIVE': 'The category you have chosen is no longer active. The category you have chosen is not active yet',
  'serverError.description.INACTIVE_USER': 'The user you are looking for is no longer active. The following user is not active yet',
  'serverError.description.INSUFFICIENT_BALANCE': 'Your balance is insufficient for processing the request',
  'serverError.description.INVALID_BET_TYPE': 'The bet type you have entered is invalid or is no longer available',
  'serverError.description.INVALID_BET_DETAILS': 'The bet details you have entered are invalid. Please, correct them',
  'serverError.description.INVALID_STAKE': 'The stake you have placed is invalid and cannot be accepted',
  'serverError.description.EMAIL_TEMPLATE_NOT_FOUND': 'The email template you are looking for could not be found. It might have been deleted permanently for specific reasons',
  'serverError.description.EMAIL_NOT_FOUND': 'The email you are looking for have entered could not be found',
  'serverError.description.BLOCKED_USER': 'The user you are looking for has been blocked for violating the website’s rules and policy',
  'serverError.description.MARKET_IS_NOT_READY_FOR_BETS': 'The following market is not available for betting yet',
  'serverError.description.EVENT_HISTORY_ID_DOES_NOT_EXIST': 'The event history ID you have entered does not exist and needs to be added',
  'serverError.description.INVALID_CATEGORY_ID': 'The Category ID you have entered is invalid',
  'serverError.description.INVALID_LEAGUE_ID': 'The League ID you have entered is invalid',
  'serverError.description.LEAGUE_TYPE_NOT_FOUND': 'The league type you are looking for could not be found',
  'serverError.description.MARKET_SELECTION_ALREADY_EXISTS': 'The market selection you are trying to create already exists',
  'serverError.description.PARTICIPANT_MEMBER_ID_MISSING': 'The member ID of the participant is missing and needs to be added',
  'serverError.description.PARTICIPANT_MEMBER_ALREADY_EXISTS': 'The participant member name you have entered already exists in the system',
  'serverError.description.PARTICIPANT_MEMBER_NOT_FOUND': 'The participant member name you have entered already exists in the system',
  'serverError.description.PARTICIPANT_NOT_FOUND': 'The participant member you are looking for could not be found',
  'serverError.description.WRONG_PARTICIPANT_TYPE': 'The participant type you have chosen is wrong and could not be accepted',
  'serverError.description.MARKET_ALREADY_EXISTS': 'The market you are trying to create already exists in the system',
  'serverError.description.INVALID_TRADING_MODE': 'The trading mode you have chosen is invalid',
  'serverError.description.INVALID_SETTINGS': 'The settings that you have chosen for this action are invalid',
  'serverError.description.INVALID_CODE': 'The code you have entered is invalid',
  'serverError.description.INVALID_CATEGORY_TYPE': 'The category type you have chosen is invalid',
  'serverError.description.MARKET_IS_NOT_IN_LEAGUE': 'The following market is not included in the corresponding league',
  'serverError.description.INVALID_EMAIL': 'The email address you have entered is invalid',
  'serverError.description.INVALID_USERNAME': 'The username you have entered is invalid',
  'serverError.description.WRONG_USERNAME_PASSWORD': 'The username, or password, or both you have entered are wrong. Please, try again',
  'serverError.description.HASH_IS_NOT_STRING': 'The hash function does not properly work in a string',
  'serverError.description.REQUEST_ALREADY_SENT': 'You have already sent the request',
  'serverError.description.EXPIRED': 'The time or session has expired',
  'serverError.description.INVALID_STRING': 'The string you have selected is invalid',
  'serverError.description.DUPLICATE': 'A duplicate of the following needs to be added',
  'serverError.description.INVALID_AMOUNT': 'The amount you have entered is invalid',
  'serverError.description.INVALID_PERMISSIONS': 'The permissions you are trying to get are invalid',
  'serverError.description.EVENT_MISSING_START_DATE': 'A start date to the following event needs to be added',
  'serverError.description.MORE_THAN_ONE_EVENT_FOUND': 'More than one event was found with the same name or details you entered',
  'serverError.description.WRONG_PARTICIPANT': 'The participant you have selected or entered is wrong or does not exist',
  'serverError.description.UNKNOWN_TABLE': 'The table you are looking for or you have entered is unknown',
  'serverError.description.INVALID_MAPPING': 'The library user is providing an invalid mapping value',
  'serverError.description.MAPPING_NOT_FOUND': 'The required type of mapping could not be found',
  'serverError.description.LEAGUE_MAPPING_NOT_FOUND': 'The required mapping of the league could not be found',
  'serverError.description.NOT_MAPPED': 'The following content has not been mapped',
  'serverError.description.PARTICIPANT_IS_NOT_IN_LEAGUE': 'The following participant is not included in the corresponding league',
  'serverError.description.SELECTION_FIXED_MIN_INVALID': 'You lack the minimum fixed amount of selections in order to be able to complete your request',
  'serverError.description.SELECTION_FIXED_MAX_INVALID': 'You have reached the fixed maximum amount of selections',
  'serverError.description.SELECTION_FIXED_MIN_MAX_CONFLICT': 'There is an error between the fixed numbers of minimum and maximum selections',
  'serverError.description.INVALID_RULE': 'The determined rule is invalid',
  'serverError.description.RESULT_NOT_FOUND': 'The result to your request could not be found',
  'serverError.description.MARKET_COMBINATION_MAX_ERROR': 'You have reached the maximum amount of market combinations',
  'serverError.description.MARKET_COMBINATION_MIN_ERROR': 'You lack the minimum amount of market combinations in order to be able to complete your request',
  'serverError.description.MARKET_SETTING_DOES_NOT_EXIST': 'The required setting for the given market does not exist in the system',
  'serverError.description.SPORT_COMBINATION_MAX_ERROR': 'You have reached the maximum amount of sport combinations',
  'serverError.description.SPORT_COMBINATION_MIN_ERROR': 'You lack the minimum amount of sport combinations in order to be able to complete your request',
  'serverError.description.COUNTRY_COMBINATION_MAX_ERROR': 'You have reached the maximum amount of country combinations',
  'serverError.description.COUNTRY_COMBINATION_MIN_ERROR': 'You lack the minimum amount of country combinations in order to be able to complete your request',
  'serverError.description.LEAGUE_COMBINATION_MAX_ERROR': 'You have reached the maximum amount of league combinations',
  'serverError.description.LEAGUE_COMBINATION_MIN_ERROR': 'You lack the minimum amount of league combinations in order to be able to complete your request',
  'serverError.description.CHANNEL_MISSING': 'The channel is missing and needs to be added',
  'serverError.description.WRONG_CHANNEL': 'The channel you have chosen or entered is wrong or does not exist',
  'serverError.description.EVENT_RESTRICTED_BET': 'The bet type you have chosen is restricted for this event or the following event has restrictions regarding certain types of bets',
  'serverError.description.LEAGUE_RESTRICTED_BET': 'The bet type you have chosen has been restricted for the given league or the following league has restrictions regarding certain types of bets',
  'serverError.description.COUNTRY_RESTRICTED_BET': 'The bet type you have chosen is restricted in this country',
  'serverError.description.SPORT_RESTRICTED_BET': 'The bet type you have chosen is restricted for this sport',
  'serverError.description.POSSIBLE_WIN_MORE_THAN_OVERASK': 'The amount of possible win exceeds the initially determined outcome amount of the bet and should go to over ask',
  'serverError.description.POSSIBLE_WIN_LESS_THAN_OVERASK': 'The amount of possible win is less than the initially determined outcome amount of the bet and should go to over ask',
  'serverError.description.BET_IN_REVIEW': 'Your bet is in review. You will be notified about the details',
  'serverError.description.STAKE_MORE_THAN_OVERASK': 'The amount of stake exceeds the initially determined outcome amount of the bet and should go to over ask',
  'serverError.description.STAKE_LESS_THAN_OVERASK': 'The amount of stake is less than the initially determined outcome amount of the bet and should go to over ask',
  'serverError.description.OVERASK_WRONG_SETTINGS': 'The settings you have selected for over ask are wrong',
  'serverError.description.USER_STAKE_LIMIT_ERROR': 'You have reached the maximum amount of stake you can place',
  'serverError.description.USER_WON_LIMIT_ERROR': 'You have reached the maximum win amount allowed on the website',
  'serverError.description.BET_WON_LIMIT_ERROR': 'You have reached the maximum amount of winning bet',
  'serverError.description.BET_STAKE_LIMIT_ERROR': 'You have reached the maximum amount of bet stake',
  'serverError.description.SELECTION_MIXED_MULTIPLES_ERROR': 'There was an error while trying to process the list of selections available for mixed multiples',
  'serverError.description.MARKET_MIXED_MULTIPLES_ERROR': 'There was an error while trying to process the list of selections available for mixed multiples within a certain market',
  'serverError.description.LEAGUE_MIXED_MULTIPLES_ERROR': 'There was an error while trying to process the list of selections available for mixed multiples within a certain league',
  'serverError.description.COUNTRY_MIXED_MULTIPLES_ERROR': 'There was an error while trying to process the list of selections available for mixed multiples within a certain country',
  'serverError.description.SPORT_MIXED_MULTIPLES_ERROR': 'There was an error while trying to process the list of selections available for mixed multiples within a certain sport',
  'serverError.description.BET_LIMIT_WRONG_SETTINGS': 'The settings you have applied for the maximum bet amount are wrong',
  'serverError.description.INVALID_DYNAMIC_LIMIT': 'The following dynamic limit is invalid',
  'serverError.description.CATEGORY_MAPPING_NOT_FOUND': 'No category mapping could be found',
  'serverError.description.SELECTION_SETTING_DOES_NOT_EXIST': 'The selection setting you have applied or entered does not exist or is not available',
  'serverError.description.SELECTION_COMBINATION_MIN_ERROR': 'You lack the minimum amount of selection combinations in order to be able to complete your request',
  'serverError.description.SELECTION_COMBINATION_MAX_ERROR': 'You have reached the maximum amount of selection combinations',
  'serverError.description.INVALID_CURRENCY': 'The currency you have entered or chosen is invalid or does not exist in the system',
  'serverError.description.EVENT_SELECTION_SETTINGS_NOT_FOUND': 'The settings you have applied for the following event selection could not be found',
  'serverError.description.EVENT_MARKET_SETTINGS_NOT_FOUND': 'The settings you have applied for the following event market could not be found',
  'serverError.description.INVALID_FIRST_NAME': 'The first name you have entered is invalid',
  'serverError.description.INVALID_LAST_NAME': 'The last name you have entered is invalid',
  'serverError.description.INVALID_BIRTHDAY': 'The birthday you have entered is invalid',
  'serverError.description.INVALID_COUNTRY': 'The country you have entered or selected is invalid as we do not provide services there',
  'serverError.description.INVALID_ADDRESS': 'The address you have entered is invalid',
  'serverError.description.INVALID_CITY': 'The city you have entered is invalid',
  'serverError.description.INVALID_STATE': 'The state you have entered is invalid',
  'serverError.description.INVALID_ZIP_CODE': 'The zip code you have entered is invalid',
  'serverError.description.INVALID_PHONE': 'The phone number you have entered is invalid',
  'serverError.description.INVALID_PASSWORD': 'The password you have entered is invalid. It should correspond to the parameters set by the website (6 characters long, no dashes, symbols, etc.)',
  'serverError.description.INVALID_ANSWER': 'The answer you have entered is invalid',
  'serverError.description.INVALID_AGE_18': 'The age you have entered is invalid. You must be at least 21 years old to register on our website',
  'serverError.description.INVALID_SECRET': 'The secret you have entered is invalid',
  // I'm here now
  'serverError.description.USER_ALREADY_EXISTS': 'A user with the same personal details already exists or user with the same name, email and / or username already exists',
  'serverError.description.PHONE_ALREADY_EXISTS': 'The phone number you have entered already exists in the system in the personal details of another user',
  'serverError.description.USERNAME_ALREADY_EXISTS': 'The username you have chosen is already in use',
  'serverError.description.EMAIL_ALREADY_EXISTS': 'The email address you have entered is already registered by another user on the website',
  'serverError.description.INVALID_QUESTION': 'The question you have entered is invalid or improper',
  'serverError.description.USER_HASH_IS_NOT_FOUND': 'The user hash could not be found in the system',
  'serverError.description.USER_HASH_IS_EXPIRED': 'The usage date or usability of the following user hash has expired',
  'serverError.description.EVENT_HAS_ACTIVE_BET': 'The following event already has an active bet',
  'serverError.description.EVENT_MARKET_HAS_ACTIVE_BET': 'The following event market has an active bet',
  'serverError.description.EVENT_SELECTION_HAS_ACTIVE_BET': 'The following event selection has an active bet',
  'serverError.description.SMS_CODE_IS_INVALID': 'The SMS code you have entered is invalid',
  'serverError.description.SMS_CODE_IS_EXPIRED': 'The SMS code availability time has expired and is no longer valid',
  'serverError.description.SMS_CODE_SENT': 'The SMS code was sent to your phone number',
  'serverError.description.SMS_CODE_IS_OFF': 'The SMS code functionality is off',
  'serverError.description.EVENT_SETTINGS_DO_NOT_EXIST': 'The event settings you have chosen do not exist in the system',
  'serverError.description.MARKET_HAS_ACTIVE_BET': 'The following market has an active bet',
  'serverError.description.USER_NOT_VERIFIED': 'Your account has not been verified yet or the following user has not been verified by our website yet',
  'serverError.description.CURRENCY_NOT_SUPPORTED': 'The currency you have chosen is not supported by the system',
  'serverError.description.TRANSACTION_NOT_FOUND': 'The transaction you are looking for could not be found in the system statistics history',
  'serverError.description.WRONG_WEBSITE_ID': 'The website ID you have entered is wrong',
  'serverError.description.PAYMENT_METHOD_NOT_SUPPORTED_FOR_THIS_WEBSITE': 'The given payment method (the payment method you have entered) is not supported by our website',
  'serverError.description.UNKNOWN_FILTER': 'The filter you have entered is unknown or does not existr',
  'serverError.description.INVALID_DOMAIN': 'The domain name you have entered is invalid or does not exist. Please, try again checking the spelling of the name',
  'serverError.description.BET_IS_NOT_IN_REVIEW': 'The following bet is not yet in review process',
  'serverError.description.INVALID_STATUS': 'The status you have reached is invalid',
  'serverError.description.SCOPE_OR_STAT_NOT_FOUND': 'We could not find the requested scope or stat',
  'serverError.description.PAYMENT_NOT_FOUND': 'The payment method or process you are looking for could not be found',
  'serverError.description.WEBSITE_NOT_FOUND': 'The website you are looking for could not be found. Check the website name, or if it is right, make sure it has not been removed permanently',
  'serverError.description.PAYMENT_DOES_NOT_SUPPORT_SELECTED_CURRENCY': 'The currency you have selected is not supported and is unavailable for the processing of the required payment',
  'serverError.description.INVALID_IP': 'Your IP address is invalid or the following IP address is invalid',
  'serverError.description.COMMUNICATION_ERROR': 'A communication error occurred while trying to process your request',
  'serverError.description.PURSE_NOT_FOUND': 'The purse you are looking for could not be found',
  'serverError.description.BANNER_ID_MISSING': 'The banner ID is missing and needs to be added.',
  'serverError.description.INVALID_REGISTRATION': 'The registration process was unsuccessful and was termed as invalid',
  'serverError.description.INVALID_PAYMENT_DETAILS': 'The payment details you have entered are invalid',
  'serverError.description.INSUFFICIENT_MERCHANT_FUNDS': 'The merchant funds you own are not sufficient enough in order to continue the request',
  'serverError.description.SOME_ELSE_EVENT_AT_THIS_TIME_SELECTED': 'A different even has already been selected for this time',
  'serverError.description.SESSION_NOT_FOUND': 'The session required for the processing of your request could not be found',
  'serverError.description.CASINO_GAME_NOT_FOUND': 'The casino game you are looking for could not be found or does not exist on the website',
  'serverError.description.PAYMEGA_API_AUTH_ERROR': 'An API authentication error occurred when trying to process your request on Paymega',
  'serverError.description.PAYMEGA_API_SETTLE_ERROR': 'An API settlement error occurred when trying to process your request on Paymega',
  'serverError.description.TRANSACTION_AUTH_FAILED': 'The system failed to carry out the authentication of your transaction. Please, try again by checking the personal and other relevant details you have entered',
  'serverError.description.TRANSACTION_SETTLE_FAILED': 'The system failed to carry out the settlement of your transaction. Please, try again by checking the personal and other relevant details you have entered',
  'serverError.description.TRANSACTION_CHECK_FAILED': 'The system failed to carry out the checking of your transaction. Please, try again by checking the personal and other relevant details you have entered',
  'serverError.description.TRANSACTION_VOID_FAILED': 'The system failed to carry out the void of your transaction. The latter could not be canceled',
  'serverError.description.UNKNOWN_DOMAIN': 'The domain name you have entered is unknown',
  'serverError.description.UNKNOWN_EMAIL_TEMPLATE': 'The email template you are looking for is unknown or does not exist',
  'serverError.description.CASINO_ID_IS_INVALID': 'The casino ID you have entered is invalid or does not exist',
  'serverError.description.PASSWORD_LENGTH_6': 'Your password should contain a minimum of 6 characters',

  'serverError.description.INVALID_TRANSACTION_DETAILS': 'The transaction details you have entered are invalid. Please, check them and try again.',
  'serverError.description.PHONE_VERIFICATION_FAILED': 'Your phone verification procedure was unsuccessful. You have either provided a wrong phone number or you have entered a wrong code. Please, try again',
  'serverError.description.WITHDRAW_MIN_LIMIT': 'The withdraw amount you have entered is less than the minimum permitted withdrawal amount',
  'serverError.description.WITHDRAW_MAX_LIMIT': 'We cannot process your request because the amount you have entered surpasses the maximum permitted withdrawal amount',
  'serverError.description.DEPOSIT_MIN_LIMIT': 'You have reached the minimum amount of deposit you can make at a time. Please, enter a lower amount',
  'serverError.description.DEPOSIT_MAX_LIMIT': 'You have reached the maximum amount of deposit you can make at a time. Please, enter a lower amount',
  'serverError.description.REGISTRATION_EMAIL_SEND_BUT_NOT_VERIFIED': 'The registration email has already been sent to you, but you have not yet verified it',
  'serverError.description.ACTIVE_BETS_ON_EVENT': 'We cannot process your request because there are still active bets on this event',
  'serverError.description.VERIFIED_DOCUMENT_CANNOT_BE_DELETED': 'This document has been verified by the website and cannot be deleted',
  'serverError.description.FIELD_IS_BLOCKED_TO_EDIT': 'You cannot edit the following field because it has been blocked',
  'serverError.description.INVALID_SOCIAL_ID': 'The ID you have entered for the following social site is invalid',

  'serverError.description.EVENT_MARKET_MAX_WINNERS': 'Your request cannot be processed because the following event market has the maximum amount of winners',
  'serverError.description.DOCUMENT_WAS_DELETED_BY_USER': 'The document you are trying to open, has been deleted by the user',
  'serverError.description.AGE_FROM_IS_NOT_NUMBER': 'The starting age can only be entered in numbers',
  'serverError.description.AGE_FROM_IS_LESS_THAN_18': 'The starting age should be 18 and above. The age you have entered is below 18',
  'serverError.description.AGE_TO_IS_NOT_NUMBER': 'The field for entering the maximum age can only be filled in with numbers',
  'serverError.description.AGE_TO_IS_NOT_BETWEEN_18_AND_100': 'The maximum age should be something between 18 and 100. The age you have entered does not correspond to this scale',
  'serverError.description.AGE_TO_IS_LESS_THAN_AGE_FROM': 'The maximum age cannot be less than the starting age, please, check your details',
  'serverError.description.INVALID_DATE': 'The date you have entered is invalid, please, try again',
}