export default {
  'serverSuccess.title.202': 'Принято',
  'serverSuccess.title.201': 'Создано',
  'serverSuccess.title.100': 'Продолжить',
  'serverSuccess.title.204': 'без содержимого',
  'serverSuccess.title.200': 'OK',
  'serverSuccess.title.206': 'частичное содержание',
  'serverSuccess.title.205': 'сброс содержания',
  'serverSuccess.title.203': 'неавторизованная информация',

  'serverSuccess.description.202': 'Код состояния – 202 Принято.  Ваш запрос был получен, но обработка еще не завершена.',
  'serverSuccess.description.201': 'Ваш запрос был успешно выполнен и ресурс был создан.',
  'serverSuccess.description.100': 'Процесс успешно работает, вы можете продолжить запрос или проигнорировать его, если это уже сделано.',
  'serverSuccess.description.200': 'Ваш запрос был технически корректным, и сервер смог ответить и обработать его должным образом.',
  'serverSuccess.description.206': 'Ваш запрос успешно обработан, а его тело содержит запрошенные диапазоны данных, описанные в заголовке RANGE запроса.',
  'serverSuccess.description.205': 'Запрос успешно завершен. Пожалуйста, сбросьте «вид документа» в начальное состояние, в котором оно было получено с исходного сервера.',
  'serverSuccess.description.203': 'Ваш запрос был успешно обработан, но прилагаемая к нему полезная нагрузка претерпела определенные изменения по сравнению с ответом 200 (OK) сервера происхождения с помощью преобразующего прокси.',

  'serverInfo.title.300': 'множественный выбор',
  'serverInfo.title.305': 'используй прокси',
  'serverError.title.502': 'Плохой шлюз',
  'serverError.title.400': 'Плохой запрос',
  'serverError.title.409': 'Конфликт',
  'serverError.title.417': 'Ожидание не выполнено',
  'serverError.title.424': 'Неудачная зависимость',
  'serverError.title.403': 'Запрещено',
  'serverError.title.504': 'Тайм-аут шлюза',
  'serverError.title.410': 'Ушел',
  'serverError.title.505': 'Версия HTTP не поддерживается',
  'serverError.title.418': 'Я - чайник',
  'serverError.title.419': 'Недостаточно места на ресурсе',
  'serverError.title.507': 'Недостаточно места',
  'serverError.title.500': 'Внутренняя ошибка сервера',
  'serverError.title.411': 'Требуемая длина',
  'serverError.title.423': 'Заблокированный',
  'serverError.title.420': 'Метод не поддерживается',
  'serverError.title.405': 'Метод не допускается',
  'serverError.title.301': 'Перемещен постоянно',
  'serverError.title.302': 'Перемещен временно',
  'serverError.title.207': 'Мульти статус',
  'serverError.title.300': 'Множественный выбор',
  'serverError.title.511': 'Требуется аутентификация сети',
  'serverError.title.406': 'Неавторизованная информация',
  'serverError.title.404': 'Страница не найдена',
  'serverError.title.501': 'Не выполнено',
  'serverError.title.402': 'Требуется оплата',
  'serverError.title.308': 'Постоянное перенаправление',
  'serverError.title.412': 'Предварительное условие не выполнено',
  'serverError.title.428': 'Требуется предварительное условие',
  'serverError.title.407': 'требуется аутентификация прокси',
  'serverError.title.431': 'поля заголовка запроса слишком большие',
  'serverError.title.408': 'тайм-аут запроса',
  'serverError.title.413': 'запрос занимает слишком много времени',
  'serverError.title.414': 'запрошенный uri слишком длинный',
  'serverError.title.416': 'запрошенный диапазон недопустим',
  'serverError.title.503': 'сервис недоступен',
  'serverError.title.101': 'переключение протоколов',
  'serverError.title.429': 'слишком много запросов',
  'serverError.title.UNAUTHORIZED': 'неразрешенный',
  'serverError.title.422': 'необработанный объект',
  'serverError.title.415': 'неподдерживаемый тип носителя',
  'serverError.title.917': 'категория не существует',

  'serverError.title.CATEGORY_ALREADY_EXISTS': 'категория уже существует',
  'serverError.title.MARKET_DOES_NOT_EXISTS': 'позиция не существует',
  'serverError.title.NO_SUCH_CODE': 'нет такого кода',
  'serverError.title.EVENT_DOES_NOT_EXIST': 'событие не существует',
  'serverError.title.INCORRECT_MARKET_CODE': 'неправильный код позиции',
  'serverError.title.NOT_SUPPORTED_EVENT_TYPE': 'не поддерживаемый тип событий',
  'serverError.title.INCORRECT_SELECTION': 'неправильный исход',
  'serverError.title.FOUND_MORE_THAN_ONE_EVENT': 'найдено более одного события',
  'serverError.title.EVENT_NOT_FOUND': 'событие не найдено',
  'serverError.title.PARTICIPANT_NOT_MAPPED': 'участник не отображен',
  'serverError.title.SPORT_NOT_MAPPED': 'спорт не отображен',
  'serverError.title.COUNTRY_NOT_MAPPED': 'страна не отображена',
  'serverError.title.LEAGUE_NOT_MAPPED': 'лига не отображена',
  'serverError.title.INCORRECT_SELECTION_TYPE': 'неправильный тип исхода',
  'serverError.title.MARKET_ID_IS_MISSING': 'ID позиции отсутствует',
  'serverError.title.MAP_ID_IS_MISSING': 'ID карты отсутствует',
  'serverError.title.QUERY_ERROR': 'ошибка запроса',
  'serverError.title.SELECTIONS_MAPPINGS_MISSING': 'маппинг исходов отсутствует',
  'serverError.title.SELECTION_MAP_ID_IS_MISSING': 'ID карты исхода отсутствует',
  'serverError.title.SELECTION_SYSTEM_ID_IS_MISSING': 'ID системы исхода отсутствует',
  'serverError.title.PROVIDER_SYSTEM_ID_IS_MISSING': 'ID провайдера отсутствует',
  'serverError.title.MARKET_MAPPINGS_MISSING': 'маппинг позиций отсутствует',
  'serverError.title.MARKET_NOT_MAPPED': 'позиция не отображена',
  'serverError.title.MARKET_NOT_FOUND': 'позиция не найдена',
  'serverError.title.EVENT_NOT_MAPPED': 'событие не найдено',
  'serverError.title.SELECTION_NOT_MAPPED': 'исход не отображен',
  'serverError.title.EVENT_MARKET_NOT_MAPPED': 'позиция событии не отображена',
  'serverError.title.UNKNOWN_PROVIDER': 'неизвестный провайдер',
  'serverError.title.PARTICIPANT_ID_MISSING': 'ID участника отсутствует',
  'serverError.title.INVALID_USER_ID': 'ID недействительного пользователя',
  'serverError.title.WRONG_ENTITY': 'неправильный субъект',
  'serverError.title.USER_ID_MISSING': 'ID пользователя отсутствует',
  'serverError.title.USER_NOT_FOUND': 'пользователь не найден',
  'serverError.title.SELECTION_DOES_NOT_EXIST': 'исход не существует',
  'serverError.title.EVENT_MARKET_NOT_FOUND': 'позиция событии не найдена',
  'serverError.title.EVENT_SELECTION_NOT_FOUND': 'исход событии не найдена',
  'serverError.title.INCORRECT_AMOUNT': 'неправильная сумма',
  'serverError.title.ACCESS_DENIED': 'доступ запрещен',
  'serverError.title.EVENT_IS_NOT_ACTIVE': 'событие не активно',
  'serverError.title.EVENT_MARKET_IS_NOT_ACTIVE': 'позиция событии не активна',
  'serverError.title.EVENT_SELECTION_IS_NOT_ACTIVE': 'исход событии не активен',
  'serverError.title.MARKET_IS_NOT_ACTIVE': 'позиция не активна',
  'serverError.title.SPORT_IS_NOT_ACTIVE': 'спорт не активен',
  'serverError.title.COUNTRY_IS_NOT_ACTIVE': 'страна не активна',
  'serverError.title.LEAGUE_IS_NOT_ACTIVE': 'лига не активна',
  'serverError.title.EVENT_SELECTION_ODD_RESTRICTION': 'исход событий имеет ограничения на коэффициентах',
  'serverError.title.COMBINATION_GROUP_RESTRICTION': 'ограничение группы комбинаций',
  'serverError.title.BAD_QUERY': 'плохой запрос',
  'serverError.title.CATEGORY_NOT_FOUND': 'категория не найдена',
  'serverError.title.UPDATE_DEFAULT_MARKET': 'обновление позиции по умолчанию',
  'serverError.title.CATEGORY_NOT_ACTIVE': 'категория не активна',
  'serverError.title.INACTIVE_USER': 'неактивный пользователь',
  'serverError.title.INSUFFICIENT_BALANCE': 'недостаточный баланс',
  'serverError.title.INVALID_BET_TYPE': 'недопустимый тип ставки',
  'serverError.title.INVALID_BET_DETAILS': 'данные ставки недействительны',
  'serverError.title.INVALID_STAKE': 'недопустимая ставка',
  'serverError.title.EMAIL_TEMPLATE_NOT_FOUND': 'шаблон электронной почты не найден',
  'serverError.title.EMAIL_NOT_FOUND': 'электронная почта не найдена',
  'serverError.title.BLOCKED_USER': 'заблокированный пользователь',
  'serverError.title.MARKET_IS_NOT_READY_FOR_BETS': 'позиция не готова к ставкам',
  'serverError.title.EVENT_HISTORY_ID_DOES_NOT_EXIST': 'ID истории событий не существует',
  'serverError.title.INVALID_CATEGORY_ID': 'недействительный ID категории',
  'serverError.title.INVALID_LEAGUE_ID': 'недействительный ID лиги',
  'serverError.title.LEAGUE_TYPE_NOT_FOUND': 'тип лиги не найден',
  'serverError.title.MARKET_SELECTION_ALREADY_EXISTS': 'исход позиции уже существует',
  'serverError.title.PARTICIPANT_MEMBER_ID_MISSING': 'ID представителя участника отсутствует',
  'serverError.title.PARTICIPANT_MEMBER_NOT_FOUND': 'представитель участника уже существует',
  'serverError.title.PARTICIPANT_NOT_FOUND': 'участник не найден',
  'serverError.title.WRONG_PARTICIPANT_TYPE': 'неправильный тип участника',
  'serverError.title.MARKET_ALREADY_EXISTS': 'позиция уже существует',
  'serverError.title.INVALID_TRADING_MODE': 'недействительный режим',
  'serverError.title.INVALID_SETTINGS': 'недействительные настройки',
  'serverError.title.INVALID_CODE': 'неверный код',
  'serverError.title.INVALID_CATEGORY_TYPE': 'недействительный тип категории',
  'serverError.title.MARKET_IS_NOT_IN_LEAGUE': 'позиции нет в лиге',
  'serverError.title.INVALID_EMAIL': 'неверный адрес электронной почты',
  'serverError.title.INVALID_USERNAME': 'неверное имя пользователя',
  'serverError.title.WRONG_USERNAME_PASSWORD': 'неправильное имя пользователя и пароль',
  'serverError.title.HASH_IS_NOT_STRING': 'хэш не в строке',
  'serverError.title.REQUEST_ALREADY_SENT': 'запрос уже отправлен',
  'serverError.title.EXPIRED': 'истекший',
  'serverError.title.INVALID_STRING': 'неверная строка',
  'serverError.title.DUPLICATE': 'копия',
  'serverError.title.INVALID_AMOUNT': 'недопустимая сумма',
  'serverError.title.INVALID_PERMISSIONS': 'неверные разрешения',
  'serverError.title.EVENT_MISSING_START_DATE': 'в событии отсутствует дата начала',
  'serverError.title.MORE_THAN_ONE_EVENT_FOUND': 'было найдено более одного события',
  'serverError.title.WRONG_PARTICIPANT': 'неправильный участник',
  'serverError.title.UNKNOWN_TABLE': 'неизвестная таблица',
  'serverError.title.INVALID_MAPPING': 'недействительный маппинг',
  'serverError.title.MAPPING_NOT_FOUND': 'маппинг не найден',
  'serverError.title.LEAGUE_MAPPING_NOT_FOUND': 'маппинг лиги не найден',
  'serverError.title.NOT_MAPPED': 'не отображен',
  'serverError.title.PARTICIPANT_IS_NOT_IN_LEAGUE': 'участник не в лиге',
  'serverError.title.SELECTION_FIXED_MIN_INVALID': 'недействительное минимальное количество исходов',
  'serverError.title.SELECTION_FIXED_MAX_INVALID': 'максимальное количество исходов',
  'serverError.title.SELECTION_FIXED_MIN_MAX_CONFLICT': 'ошибка между минимальным и максимальным количеством исходов',
  'serverError.title.INVALID_RULE': 'недействительное правило',
  'serverError.title.RESULT_NOT_FOUND': 'результат не найден',
  'serverError.title.MARKET_COMBINATION_MAX_ERROR': 'ошибка максимальных позиционных комбинаций',
  'serverError.title.MARKET_COMBINATION_MIN_ERROR': 'ошибка минимальных позиционных комбинаций',
  'serverError.title.MARKET_SETTING_DOES_NOT_EXIST': 'настройка позиции не существует',
  'serverError.title.SPORT_COMBINATION_MAX_ERROR': 'ошибка максимальных комбинаций спорта',
  'serverError.title.SPORT_COMBINATION_MIN_ERROR': 'ошибка минимальных комбинаций спорта',
  'serverError.title.COUNTRY_COMBINATION_MAX_ERROR': 'ошибка минимальных комбинаций страны',
  'serverError.title.COUNTRY_COMBINATION_MIN_ERROR': 'ошибка минимальных комбинаций страны',
  'serverError.title.LEAGUE_COMBINATION_MAX_ERROR': 'ошибка максимальных комбинаций лиги',
  'serverError.title.LEAGUE_COMBINATION_MIN_ERROR': 'ошибка минимальных комбинаций лиги',
  'serverError.title.CHANNEL_MISSING': 'канал отсутствует',
  'serverError.title.WRONG_CHANNEL': 'неправильный канал',
  'serverError.title.EVENT_RESTRICTED_BET': 'ограничения на типы ставок для событий',
  'serverError.title.LEAGUE_RESTRICTED_BET': 'ограничения на типы ставок для лиг',
  'serverError.title.COUNTRY_RESTRICTED_BET': 'ограничения на типы ставок для стран',
  'serverError.title.SPORT_RESTRICTED_BET': 'ограничения на типы ставок для спорта',
  'serverError.title.POSSIBLE_WIN_MORE_THAN_OVERASK': 'возможный выигрыш больше чем перегрузка',
  'serverError.title.POSSIBLE_WIN_LESS_THAN_OVERASK': 'возможный выигрыш меньше чем перегрузка',
  'serverError.title.BET_IN_REVIEW': 'ставка в обзоре',
  'serverError.title.STAKE_MORE_THAN_OVERASK': 'ставка больше чем перегрузка',
  'serverError.title.STAKE_LESS_THAN_OVERASK': 'ставка меньше чем перегрузка',
  'serverError.title.OVERASK_WRONG_SETTINGS': 'неправильные настройки перегрузки',
  'serverError.title.USER_STAKE_LIMIT_ERROR': 'ошибка - ограничение суммы ставки пользователя',
  'serverError.title.USER_WON_LIMIT_ERROR': 'ошибка - ограничение выигранной суммы пользователя',
  'serverError.title.BET_WON_LIMIT_ERROR': 'ошибка – ограничение суммы выигрышной ставки',
  'serverError.title.BET_STAKE_LIMIT_ERROR': 'ошибка – ограничение суммы ставки',
  'serverError.title.SELECTION_MIXED_MULTIPLES_ERROR': 'ошибка исходов экспресс ставки',
  'serverError.title.MARKET_MIXED_MULTIPLES_ERROR': 'ошибка позиций экспресс ставки',
  'serverError.title.LEAGUE_MIXED_MULTIPLES_ERROR': 'ошибка лиги экспресс ставки',
  'serverError.title.COUNTRY_MIXED_MULTIPLES_ERROR': 'ошибка страны экспресс ставки',
  'serverError.title.SPORT_MIXED_MULTIPLES_ERROR': 'ошибка спорта экспресс ставки',
  'serverError.title.BET_LIMIT_WRONG_SETTINGS': 'неправильные настройки предела ставки',
  'serverError.title.INVALID_DYNAMIC_LIMIT': 'недействительные динамические лимиты',
  'serverError.title.CATEGORY_MAPPING_NOT_FOUND': 'маппинг категории не найден',
  'serverError.title.SELECTION_SETTING_DOES_NOT_EXIST': 'настройка исхода не существует',
  'serverError.title.SELECTION_COMBINATION_MIN_ERROR': 'ошибка минимальных комбинаций исходов',
  'serverError.title.SELECTION_COMBINATION_MAX_ERROR': 'ошибка максимальных комбинаций исходов',
  'serverError.title.INVALID_CURRENCY': 'недействительная валюта',
  'serverError.title.EVENT_SELECTION_SETTINGS_NOT_FOUND': 'настройки исхода события не найдены',
  'serverError.title.EVENT_MARKET_SETTINGS_NOT_FOUND': 'настройки позиции события не найдены',
  'serverError.title.INVALID_FIRST_NAME': 'недопустимое имя',
  'serverError.title.INVALID_LAST_NAME': 'недопустимая фамилия',
  'serverError.title.INVALID_BIRTHDAY': 'неверный день рождения',
  'serverError.title.INVALID_COUNTRY': 'недопустимая страна',
  'serverError.title.INVALID_ADDRESS': 'неверный адрес',
  'serverError.title.INVALID_CITY': 'недопустимый город',
  'serverError.title.INVALID_STATE': 'неверная область или неверный край',
  'serverError.title.INVALID_ZIP_CODE': 'неверный почтовый индекс',
  'serverError.title.INVALID_PHONE': 'неправильный номер телефона',
  'serverError.title.INVALID_PASSWORD': 'неправильный пароль',
  'serverError.title.INVALID_ANSWER': 'неверный ответ',
  'serverError.title.INVALID_AGE_18': 'недопустимый возраст 18',
  'serverError.title.INVALID_SECRET': 'недействительный секрет',
  'serverError.title.USER_ALREADY_EXISTS': 'пользователь уже существует',
  'serverError.title.PHONE_ALREADY_EXISTS': 'номер телефона уже существует',
  'serverError.title.USERNAME_ALREADY_EXISTS': 'имя пользователя уже существует',
  'serverError.title.EMAIL_ALREADY_EXISTS': 'адрес электронной почты уже существует',
  'serverError.title.INVALID_QUESTION': 'неверный вопрос',
  'serverError.title.USER_HASH_IS_NOT_FOUND': 'хэш пользователя не найден',
  'serverError.title.USER_HASH_IS_EXPIRED': 'хэш пользователя истек',
  'serverError.title.EVENT_HAS_ACTIVE_BET': 'событие имеет активную ставку',
  'serverError.title.EVENT_MARKET_HAS_ACTIVE_BET': 'позиция событии имеет активную ставку',
  'serverError.title.EVENT_SELECTION_HAS_ACTIVE_BET': 'исход событии имеет активную ставку',
  'serverError.title.SMS_CODE_IS_INVALID': 'неверный смс-код',
  'serverError.title.SMS_CODE_IS_EXPIRED': 'срок действия смс-кода истек',
  'serverError.title.SMS_CODE_SENT': 'смс-код отправлен',
  'serverError.title.SMS_CODE_IS_OFF': 'смс-код отключен',
  'serverError.title.EVENT_SETTINGS_DO_NOT_EXIST': 'настройки событий не существуют',
  'serverError.title.MARKET_HAS_ACTIVE_BET': 'позиция имеет активную ставку',
  'serverError.title.USER_NOT_VERIFIED': 'пользователь не потвержден',
  'serverError.title.CURRENCY_NOT_SUPPORTED': 'валюта не поддерживается',
  'serverError.title.TRANSACTION_NOT_FOUND': 'транзакция не найдена',
  'serverError.title.WRONG_WEBSITE_ID': 'неправильный id сайта',
  'serverError.title.PAYMENT_METHOD_NOT_SUPPORTED_FOR_THIS_WEBSITE': 'не поддерживаемый метод оплаты',
  'serverError.title.UNKNOWN_FILTER': 'неизвестный фильтр',
  'serverError.title.INVALID_DOMAIN': 'недействительный домен',
  'serverError.title.BET_IS_NOT_IN_REVIEW': 'ставка не в обзоре',
  'serverError.title.INVALID_STATUS': 'недействительный статус',
  'serverError.title.SCOPE_OR_STAT_NOT_FOUND': 'область применения или статус не найдены',
  'serverError.title.PAYMENT_NOT_FOUND': 'платеж не найден',
  'serverError.title.WEBSITE_NOT_FOUND': 'сайт не найден',
  'serverError.title.PAYMENT_DOES_NOT_SUPPORT_SELECTED_CURRENCY': 'метод оплаты не поддерживает выбранную валюту',
  'serverError.title.INVALID_IP': 'неверный ip-адрес',
  'serverError.title.COMMUNICATION_ERROR': 'ошибка связи',
  'serverError.title.PURSE_NOT_FOUND': 'кошелек не найден',
  'serverError.title.BANNER_ID_MISSING': 'ID баннера отсутствует',
  'serverError.title.INVALID_REGISTRATION': 'неправильная регистрация',
  'serverError.title.INVALID_PAYMENT_DETAILS': 'неправильные данные платежа',
  'serverError.title.INSUFFICIENT_MERCHANT_FUNDS': 'торговые средства являются недостаточными',
  'serverError.title.SOME_ELSE_EVENT_AT_THIS_TIME_SELECTED': 'в это время было выбрано другое событие',
  'serverError.title.SESSION_NOT_FOUND': 'сессия не найдена',
  'serverError.title.CASINO_GAME_NOT_FOUND': 'казино игра не найдена',
  'serverError.title.PAYMEGA_API_AUTH_ERROR': 'ошибка аутентификации paymega api',
  'serverError.title.PAYMEGA_API_SETTLE_ERROR': 'ошибка расчета paymega api',
  'serverError.title.TRANSACTION_AUTH_FAILED': 'ошибка аутентификации транзакции',
  'serverError.title.TRANSACTION_SETTLE_FAILED': 'расчет транзакции не выполнен',
  'serverError.title.TRANSACTION_CHECK_FAILED': 'проверка транзакции не удалась',
  'serverError.title.TRANSACTION_VOID_FAILED': 'аннулирование транзакции не выполнено',
  'serverError.title.UNKNOWN_DOMAIN': 'неизвестный домен',
  'serverError.title.UNKNOWN_EMAIL_TEMPLATE': 'неизвестный шаблон электронной почты',
  'serverError.title.CASINO_ID_IS_INVALID': 'ID казино недействителен',
  'serverError.title.PASSWORD_LENGTH_6': 'длина пароля 6',

  'serverError.title.INVALID_TRANSACTION_DETAILS': 'данные транзакции недействительны',
  'serverError.title.PHONE_VERIFICATION_FAILED': 'верификация номера телефона не удалось',
  'serverError.title.WITHDRAW_MIN_LIMIT': 'минимальный лимит вывода',
  'serverError.title.WITHDRAW_MAX_LIMIT': 'максимальный лимит вывода',
  'serverError.title.DEPOSIT_MIN_LIMIT': 'минимальный лимит депозита',
  'serverError.title.DEPOSIT_MAX_LIMIT': 'максимальный лимит депозита',
  'serverError.title.REGISTRATION_EMAIL_SEND_BUT_NOT_VERIFIED': 'регистрационная электронная почта отправлена, но не подтверждена',
  'serverError.title.ACTIVE_BETS_ON_EVENT': 'активные ставки на событие',
  'serverError.title.VERIFIED_DOCUMENT_CANNOT_BE_DELETED': 'подтвержденный документ не может быть удален',
  'serverError.title.FIELD_IS_BLOCKED_TO_EDIT': 'поле блокировано для изменения',
  'serverError.title.INVALID_SOCIAL_ID': 'социальный ID недействителен',

  'serverError.title.EVENT_MARKET_MAX_WINNERS': 'позиция событии имеет максимальное количество победителей',
  'serverError.title.DOCUMENT_WAS_DELETED_BY_USER': 'документ был удален пользователем',
  'serverError.title.AGE_FROM_IS_NOT_NUMBER': '‘возраст от’ не число',
  'serverError.title.AGE_FROM_IS_LESS_THAN_18': '‘возраст от’ меньше 18-ти',
  'serverError.title.AGE_TO_IS_NOT_NUMBER': '‘возраст до’ не число',
  'serverError.title.AGE_TO_IS_NOT_BETWEEN_18_AND_100': '‘возраст до’ не между 18 и 100',
  'serverError.title.AGE_TO_IS_LESS_THAN_AGE_FROM': '‘возраст до’ меньше ‘возраста от’ ',
  'serverError.title.INVALID_DATE': 'недействительная дата',

  'serverError.description.502': 'Ошибка сервера: Ваш запрос не может быть завершен, так как прокси-сервер наткнулся на временную ошибку.',
  'serverError.description.400': 'Ваш браузер отправил запрос, который сервер не мог понять. Размер поля заголовка запроса превышает лимит сервера. ',
  'serverError.description.409': 'У вашего запроса был недопустимый заголовок идентификатора сеанса. Повторите попытку позже или обратитесь к системному администратору.',
  'serverError.description.417': 'Ожидание, указанное в запросе с заголовком Expect, не может быть выполнено текущим сервером.',
  'serverError.description.424': 'Ваш запрос не может быть обработан в результате отказа предыдущего запроса. Пожалуйста, попробуйте еще раз!  ',
  'serverError.description.403': 'У вас нет разрешения на доступ к текущему серверу.',
  'serverError.description.504': 'Произошла ошибка ТАЙМ-АУТ ШЛЮЗА, из-за которой сервер недоступен. Пожалуйста, повторите запрос!',
  'serverError.description.410': `Страница не существует или была удалена. 
                                  Запрошенный вами источник недоступен на этом сервере, и у нас нет адреса пересылки. Это может быть из-за нескольких причин: 
                                    <ul>
                                        <li>Введенный вами веб-адрес неверен или, </li>
                                        <li>Страница, которую вы ищете, была удалена навсегда.</li>
                                    </ul>
                                  Повторите попытку или обратитесь к администратору сервера.  
                                 `,
  'serverError.description.505': 'Версия HTTP, используемая в вашем запросе, недействительна или не поддерживается нашим сервером. Пожалуйста, попробуйте еще раз!',
  'serverError.description.418': 'Запрошенный объект является коротким и толстым. Поднимите меня и вылейте. Ваш запрос на кофе был отклонен, так как наш сервер является чайником.',
  'serverError.description.419': 'Произошла непредвиденная ошибка, что означает, что для выполнения операции недостаточно места на диске. Проверьте журнал сервера для получения более подробной информации.',
  'serverError.description.507': 'Сервер не может сохранить представление, необходимое для выполнения и завершения вашего запроса.',
  'serverError.description.500': 'Сервер наткнулся на внутреннюю ошибку или неправильную конфигурацию, из-за которой завершение вашего запроса было прервано. Пожалуйста, свяжитесь с администратором сервера для решения проблемы.',
  'serverError.description.411': 'Сервер отказывается принять ваш запрос без определенной длины контента. Вы можете попробовать отправить запрос еще раз, если добавлено допустимое поле заголовка Content-Length с соответствующим телом сообщения в сообщении запроса. ',
  'serverError.description.423': 'Сервер отказывается обработать запрос, так как один из требуемых ресурсов заблокирован.',
  'serverError.description.420': 'Произошла системная ошибка. Причиной этого может быть повреждение файлов вашей системы Windows. Повторите попытку отправки запроса или обратитесь к администратору сервера.',
  'serverError.description.405': 'Метод, указанный в строке запроса, не разрешен для ресурса, идентифицированного Request-URI.',
  'serverError.description.301': 'Запрошенному ресурсу был приписан новый постоянный URI, поэтому любые дополнительные ссылки на ресурс должны использовать один из возвращенных URI.',
  'serverError.description.302': 'Была ошибка во время соединения с сервером. Запрошенный ресурс временно находится под другим URI. Поскольку перенаправление может иногда изменяться, продолжайте использовать Request-URI для будущих запросов.',
  'serverError.description.207': 'При попытке обработать ваш запрос, произошла ошибка. Кажется, что было выполнено несколько операций, и вы можете найти статус для каждой операции в теле ответа.',
  'serverError.description.511': 'Вам необходимо пройти процесс аутентификации, чтобы получить доступ к сети.',
  'serverError.description.406': 'Ваш запрос не является приемлемым. Соответствующее представление запрошенного ресурса не найдено на этом сервере.',
  'serverError.description.404': 'При попытке обработать ваш запрос произошла ошибка. Сервер не смог найти то, что вы запросили.',
  'serverError.description.501': 'При обработке вашего запроса произошла ошибка сервера. Сервер либо не распознает метод вашего запроса, либо не выполняет функции его выполнения.',
  'serverError.description.402': 'Сервер наткнулся на внутреннюю ошибку или неправильную конфигурацию и не смог обработать ваш запрос. Пожалуйста, свяжитесь с администратором сервера и сообщите им о времени ошибки, а также о действиях, которые вы предприняли до того, как это произошло. Журнал ошибок сервера также может предоставить вам дополнительную информацию по этому вопросу. ',
  'serverError.description.412': 'Ваш запрос не может быть обработан из-за предусловий, заданных в заголовке запроса. Эти предварительные условия не позволяют применить запрошенный метод к ресурсу, за исключением того, что предназначено.',
  'serverError.description.308': 'Запрашиваемая страница была постоянно перемещена. ',
  'serverError.description.407': 'Сервер не может выполнить запрос, поскольку вам не хватает необходимых учетных данных для прокси-сервера.',
  'serverError.description.428': 'Сервер требует, чтобы ваш запрос был условным (соответствовал неким предварительно заданным условиям). Как правило, это означает, что требуемый заголовок предварительного условия, например, If-Match отсутствует.',
  'serverError.description.431': 'Сервер не желает обрабатывать ваш запрос, потому что поля заголовка слишком велики. Если уменьшить размер полей заголовка запроса, то запрос может быть повторно отправлен и обработан до завершения. ',
  'serverError.description.408': 'Ваш браузер не смог отправить полный запрос вовремя, поэтому запрос был перерван сервером. Пожалуйста, свяжитесь с администратором сервера, чтобы продлить процесс «Время ожидания соединения», если вы считаете, что ваш запрос не должен был быть отключен.',
  'serverError.description.413': 'При попытке обработать ваш запрос произошла ошибка. Запрошенный ресурс не позволяет запрашивать данные с запросами POST или объем данных, представленных в запросе, превышает ограничение емкости. ',
  'serverError.description.414': `URI, к которому вы хотите получить доступ, слишком длинный.`,
  'serverError.description.416': 'Запрошенные диапазоны не могут обслуживаться сервером, потому что, либо ваш документ не содержит заданных диапазонов, либо значение заголовка RANGE несовместимо с каким-либо соответствующим значением. ',
  'serverError.description.503': 'Сервер временно перестал принимать новые запросы, из-за слишком длинной очереди запросов. Пожалуйста, попробуйте позже.',
  'serverError.description.101': 'Запрашиваемый вами протокол переключается сервером. Было отправлено сообщение, включая заголовок запроса UPGRADE.',
  'serverError.description.429': 'Ваш IP-адрес вызвал слишком много запросов к текущей службе за короткий промежуток времени. Пожалуйста, попробуйте позже.',
  'serverError.description.UNAUTHORIZED': 'В результате недопустимых учетных данных запрещается доступ к странице или каталогу.',
  'serverError.description.422': 'Запрошенное изменение не может быть обработано и отклонено.',
  'serverError.description.415': 'Ваш запрос был отклонен из-за того, что ресурс был в формате, который не поддерживается сервером.',
  'serverError.description.917': 'При попытке обработать ваш запрос произошла ошибка. Повторите попытку позже или свяжитесь с администратором сервера для получения дополнительных инструкций.',

  'serverError.description.CATEGORY_ALREADY_EXISTS': 'Категория с тем же именем уже существует.',
  'serverError.description.MARKET_DOES_NOT_EXISTS': 'Позиция, которую вы ищете, не существует.',
  'serverError.description.NO_SUCH_CODE': 'Мы не смогли найти соответствующий ответ на введенный вами код.',
  'serverError.description.EVENT_DOES_NOT_EXIST': 'Событие, которое вы ищете, не существует.',
  'serverError.description.INCORRECT_MARKET_CODE': 'Введен неверный код позиции.',
  'serverError.description.NOT_SUPPORTED_EVENT_TYPE': 'Тип события, который вы создаете или выбираете, не поддерживается системой.',
  'serverError.description.INCORRECT_SELECTION': 'Введенное вами имя исхода неверно.',
  'serverError.description.FOUND_MORE_THAN_ONE_EVENT': 'Мы нашли более одного события, соответствующего вашему запросу.',
  'serverError.description.EVENT_NOT_FOUND': 'Невозможно найти событие, которое вы ищете.',
  'serverError.description.PARTICIPANT_NOT_MAPPED': 'Участник не был отображен и добавлен в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.SPORT_NOT_MAPPED': 'Спорт не был отображен и добавлен в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.COUNTRY_NOT_MAPPED': 'Страна не была отображена и добавлена в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.LEAGUE_NOT_MAPPED': 'Лига не была отображена и добавлена в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.INCORRECT_SELECTION_TYPE': 'Вы ввели неправильный тип исхода.',
  'serverError.description.MARKET_ID_IS_MISSING': 'Вы не определили ID позиции.',
  'serverError.description.MAP_ID_IS_MISSING': 'Вы не определили ID карты.',
  'serverError.description.QUERY_ERROR': 'При попытке обработать ваш запрос произошла ошибка.',
  'serverError.description.SELECTIONS_MAPPINGS_MISSING': 'Маппинг исходов отсутствует и должен быть добавлен.',
  'serverError.description.SELECTION_MAP_ID_IS_MISSING': 'Вы не определили ID карты исхода.',
  'serverError.description.SELECTION_SYSTEM_ID_IS_MISSING': 'Вы не определили ID системы исхода.',
  'serverError.description.PROVIDER_SYSTEM_ID_IS_MISSING': 'Вы не определили ID провайдера.',
  'serverError.description.MARKET_MAPPINGS_MISSING': 'Маппинг позиций отсутствует и должен быть добавлен.',
  'serverError.description.MARKET_NOT_MAPPED': 'Позиция не была отображена и добавлена в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.MARKET_NOT_FOUND': 'Позиция, которую вы ищете, не найдена.',
  'serverError.description.EVENT_NOT_MAPPED': 'Событие не было отображено и добавлено в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.SELECTION_NOT_MAPPED': 'Исход не был отображен и добавлен в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.EVENT_MARKET_NOT_MAPPED': 'Позиция не была отображена и добавлена в соответствующую позицию из-за отсутствия необходимых ресурсов.',
  'serverError.description.UNKNOWN_PROVIDER': 'Провайдер которого вы выбрали, неизвестен системе.',
  'serverError.description.PARTICIPANT_ID_MISSING': 'ID участника отсутствует и его необходимо добавить.',
  'serverError.description.INVALID_USER_ID': 'ID пользователя, который вы выбрал или который вы ищете, недействителен, или уже существует в системе, или не найден.',
  'serverError.description.WRONG_ENTITY': 'Введенный вами субъект ошибочен или недоступен или субъект, который вы выбрали, не соответствует списку субъектов и / или правилам системы. ',
  'serverError.description.USER_ID_MISSING': 'ID пользователя должен быть добавлен, поскольку он еще не определен и отсутствует.',
  'serverError.description.USER_NOT_FOUND': 'Пользователь, которого вы ищете, не найден.',
  'serverError.description.SELECTION_DOES_NOT_EXIST': 'Исход, который вы ищете не существует в системе.',
  'serverError.description.EVENT_MARKET_NOT_FOUND': 'Невозможно найти позиция событии, которую вы ищете.',
  'serverError.description.EVENT_SELECTION_NOT_FOUND': 'Исход событии, который вы ищете не найден.',
  'serverError.description.INCORRECT_AMOUNT': 'Введенная вами сумма неверна.',
  'serverError.description.ACCESS_DENIED': 'К сожалению, вы не можете получить доступ к следующим данным или к следующему разделу или к следующей информации. ',
  'serverError.description.EVENT_IS_NOT_ACTIVE': 'Событие, которое вы пытаетесь открыть, больше неактивно.',
  'serverError.description.EVENT_MARKET_IS_NOT_ACTIVE': 'Позиция событии, к которой вы пытаетесь получить доступ, больше не активна.',
  'serverError.description.EVENT_SELECTION_IS_NOT_ACTIVE': 'Исход событии, к которому вы пытаетесь получить доступ, больше не активен.',
  'serverError.description.MARKET_IS_NOT_ACTIVE': 'Позиция, к которой вы пытаетесь получить доступ, больше не активна.',
  'serverError.description.SPORT_IS_NOT_ACTIVE': 'Следующий вид спорта больше не активен.',
  'serverError.description.COUNTRY_IS_NOT_ACTIVE': 'Страна, которую вы хотите ввести или выбрать, неактивна.',
  'serverError.description.LEAGUE_IS_NOT_ACTIVE': 'Лига, к которой вы хотите получить доступ, больше не активна.',
  'serverError.description.EVENT_SELECTION_ODD_RESTRICTION': 'Вы достигли наивысшей точки ограничений на коэффициентах исходов событий.',
  'serverError.description.COMBINATION_GROUP_RESTRICTION': 'Вы достигли максимального количества групп комбинаций.',
  'serverError.description.BAD_QUERY': 'При попытке обработать ваш запрос произошла ошибка. Пожалуйста, попробуйте еще раз.  ',
  'serverError.description.CATEGORY_NOT_FOUND': 'Категория, которую вы ищете, не найдена.',
  'serverError.description.UPDATE_DEFAULT_MARKET': 'Обновить позицию по умолчанию.',
  'serverError.description.CATEGORY_NOT_ACTIVE': 'Выбранная вами категория больше не активна или категория, которую вы выбрали, пока неактивна.',
  'serverError.description.INACTIVE_USER': 'Пользователь, которого вы ищете, больше не активен или пользователь, которого вы выбрали, пока не активен.',
  'serverError.description.INSUFFICIENT_BALANCE': 'Для обработки запроса Ваш баланс недостаточен.',
  'serverError.description.INVALID_BET_TYPE': 'Тип ставки, введенный вами, недействителен или больше не доступен. ',
  'serverError.description.INVALID_BET_DETAILS': 'Введенные вами данные ставки недействительны. Пожалуйста, исправьте их.',
  'serverError.description.INVALID_STAKE': 'Поставленная вами ставка недействительна и не может быть принята.',
  'serverError.description.EMAIL_TEMPLATE_NOT_FOUND': 'Не удалось найти шаблон электронной почты, который вы ищете. Возможно, он был удален по определенным причинам.',
  'serverError.description.EMAIL_NOT_FOUND': 'Не удалось найти адрес электронной почты, который вы ищете или указали.',
  'serverError.description.BLOCKED_USER': 'Пользователь, которого вы ищете, заблокирован за нарушение правил и политики сайта.',
  'serverError.description.MARKET_IS_NOT_READY_FOR_BETS': 'Следующая позиция еще не доступна для ставок.',
  'serverError.description.EVENT_HISTORY_ID_DOES_NOT_EXIST': 'ID истории событий, который вы ввели, не существует и должен быть добавлен.',
  'serverError.description.INVALID_CATEGORY_ID': 'ID категории, который вы ввели, недействителен.',
  'serverError.description.INVALID_LEAGUE_ID': 'ID лиги введенный вами, недействителен.',
  'serverError.description.LEAGUE_TYPE_NOT_FOUND': 'Тип лиги, который вы ищете, не найден.',
  'serverError.description.MARKET_SELECTION_ALREADY_EXISTS': 'Исход позиции, который вы пытаетесь создать, уже существует.',
  'serverError.description.PARTICIPANT_MEMBER_ID_MISSING': 'ID представителя участника отсутствует и его необходимо добавить.',
  'serverError.description.PARTICIPANT_MEMBER_ALREADY_EXISTS': 'Имя представителя участника, которое вы ввели, уже существует в системе.',
  'serverError.description.PARTICIPANT_MEMBER_NOT_FOUND': 'Не удалось найти представителя участника, которого вы ищете.',
  'serverError.description.PARTICIPANT_NOT_FOUND': 'Не удалось найти участника, которого вы ищете.',
  'serverError.description.WRONG_PARTICIPANT_TYPE': 'Тип участника, который вы выбрали, неверен и не может быть принят.',
  'serverError.description.MARKET_ALREADY_EXISTS': 'Позиция, которую вы пытаетесь создать, уже существует в системе.',
  'serverError.description.INVALID_TRADING_MODE': 'Режим, который вы выбрали, недействителен.',
  'serverError.description.INVALID_SETTINGS': 'Настройки, которые вы выбрали для этого действия являются недействительными.',
  'serverError.description.INVALID_CODE': 'Введенный вами код недействителен.',
  'serverError.description.INVALID_CATEGORY_TYPE': 'Тип категории, который вы выбрали недействителен.',
  'serverError.description.MARKET_IS_NOT_IN_LEAGUE': 'Следующая позиция не включен в соответствующую лигу.',
  'serverError.description.INVALID_EMAIL': 'Введенный вами адрес электронной почты недействителен.',
  'serverError.description.INVALID_USERNAME': 'Введенное вами имя пользователя недействительно.',
  'serverError.description.WRONG_USERNAME_PASSWORD': 'Имя пользователя и / или пароль, который вы ввели неверны. Пожалуйста, повторите попытку.  ',
  'serverError.description.HASH_IS_NOT_STRING': 'Хеш-функция не работает должным образом в строке.',
  'serverError.description.REQUEST_ALREADY_SENT': 'Вы уже отправили запрос.',
  'serverError.description.EXPIRED': 'Время сессии истекло.',
  'serverError.description.INVALID_STRING': 'Выбранная строка недействительна.',
  'serverError.description.DUPLICATE': 'Необходимо добавить копию следующего содержания.',
  'serverError.description.INVALID_AMOUNT': 'Введенная вами сумма недопустима.',
  'serverError.description.INVALID_PERMISSIONS': 'Разрешения, которые вы пытаетесь получить, являются неверными.',
  'serverError.description.EVENT_MISSING_START_DATE': 'Необходимо добавить дату начала следующего события.',
  'serverError.description.MORE_THAN_ONE_EVENT_FOUND': 'Было найдено более одного события с тем же именем или данными, которые вы ввели.',
  'serverError.description.WRONG_PARTICIPANT': 'Участник, выбранный вами или введенный вами, ошибочен или не существует.',
  'serverError.description.UNKNOWN_TABLE': 'Таблица, которую вы ищете или вы ввели, неизвестна.',
  'serverError.description.INVALID_MAPPING': 'Пользователь библиотеки предоставляет недопустимое маппинг значение.',
  'serverError.description.MAPPING_NOT_FOUND': 'Не удалось найти требуемый тип маппинга.',
  'serverError.description.LEAGUE_MAPPING_NOT_FOUND': 'Не удалось найти требуемый маппинг лиги.',
  'serverError.description.NOT_MAPPED': 'Следующий контент не был отображен.',
  'serverError.description.PARTICIPANT_IS_NOT_IN_LEAGUE': 'Следующий участник не включен в соответствующую лигу.',
  'serverError.description.SELECTION_FIXED_MIN_INVALID': 'Вам не хватает минимального количества исходов, чтобы выполнить ваш запрос.',
  'serverError.description.SELECTION_FIXED_MAX_INVALID': 'Вы достигли максимального количества исходов.',
  'serverError.description.SELECTION_FIXED_MIN_MAX_CONFLICT': 'Произошла ошибка между минимальным и максимальным количеством исходов. ',
  'serverError.description.INVALID_RULE': 'Определенное правило недействительно.',
  'serverError.description.RESULT_NOT_FOUND': 'Результат по вашему запросу не найден.',
  'serverError.description.MARKET_COMBINATION_MAX_ERROR': 'Вы достигли максимального количества позиционных комбинаций.',
  'serverError.description.MARKET_COMBINATION_MIN_ERROR': 'Вам не хватает минимального количества позиционных комбинаций для завершения вашего запроса.',
  'serverError.description.MARKET_SETTING_DOES_NOT_EXIST': 'Необходимая настройка для данной позиции в системе отсутствует.',
  'serverError.description.SPORT_COMBINATION_MAX_ERROR': 'Вы достигли максимального количества спортивных комбинаций.',
  'serverError.description.SPORT_COMBINATION_MIN_ERROR': 'Вам не хватает минимального количества спортивных комбинаций, чтобы выполнить ваш запрос.',
  'serverError.description.COUNTRY_COMBINATION_MAX_ERROR': 'You have reached the maximum amount of country combinations',
  'serverError.description.COUNTRY_COMBINATION_MIN_ERROR': 'Вы достигли максимального количества комбинаций стран.',
  'serverError.description.LEAGUE_COMBINATION_MAX_ERROR': 'Вам не хватает минимального количества комбинаций стран, чтобы выполнить ваш запрос.',
  'serverError.description.LEAGUE_COMBINATION_MIN_ERROR': 'Вы достигли максимального количества комбинаций лиги.',
  'serverError.description.CHANNEL_MISSING': 'Канал отсутствует и должен быть добавлен.',
  'serverError.description.WRONG_CHANNEL': 'Канал, который вы выбрали или ввели, неверен или не существует.',
  'serverError.description.EVENT_RESTRICTED_BET': 'Тип ставки, который вы выбрали, ограничен для этого события или следующее событие имеет ограничения в отношении определенных типов ставок. ',
  'serverError.description.LEAGUE_RESTRICTED_BET': 'Тип ставки, который вы выбрали, был ограничен для данной лиги или мледующая лига имеет ограничения в отношении определенных типов ставок.',
  'serverError.description.COUNTRY_RESTRICTED_BET': 'Тип ставки, который вы выбрали, ограничен в этой стране.',
  'serverError.description.SPORT_RESTRICTED_BET': 'Тип ставки, который вы выбрали, ограничен для этого вида спорта.',
  'serverError.description.POSSIBLE_WIN_MORE_THAN_OVERASK': 'Сумма возможного выигрыша превышает первоначально определенную сумму результата ставки и должна переходить к перегрузке.',
  'serverError.description.POSSIBLE_WIN_LESS_THAN_OVERASK': 'Сумма возможного выигрыша меньше, чем первоначально определенная сумма результата ставки и должна переходить к перегрузке.  ',
  'serverError.description.BET_IN_REVIEW': 'Ваша ставка рассматривается. Вы будете уведомлены о деталях. ',
  'serverError.description.STAKE_MORE_THAN_OVERASK': 'Сумма ставки превышает первоначально определенную сумму результата ставки и должна переходить к перегрузке.',
  'serverError.description.STAKE_LESS_THAN_OVERASK': 'Сумма ставки меньше, чем первоначально определенная сумма результата ставки и должна переходить к перегрузке.',
  'serverError.description.OVERASK_WRONG_SETTINGS': 'Настройки, которые вы выбрали для перегрузки, неверны.',
  'serverError.description.USER_STAKE_LIMIT_ERROR': 'Вы достигли максимального количества ставки, которую вы можете разместить.',
  'serverError.description.USER_WON_LIMIT_ERROR': 'Вы достигли максимальной суммы выигрыша, разрешенной на веб-сайте.',
  'serverError.description.BET_WON_LIMIT_ERROR': 'Вы достигли максимального количества выигрышной ставки.',
  'serverError.description.BET_STAKE_LIMIT_ERROR': 'Вы достигли максимальной суммы ставки.',
  'serverError.description.SELECTION_MIXED_MULTIPLES_ERROR': 'При попытке обработать список исходов, доступных для экспресс ставки, произошла ошибка.',
  'serverError.description.MARKET_MIXED_MULTIPLES_ERROR': 'При попытке обработать список исходов, доступных для экспресс ставки на определенной позиции, произошла ошибка.',
  'serverError.description.LEAGUE_MIXED_MULTIPLES_ERROR': 'При попытке обработать список исходов, доступных для экспресс ставки в определенной лиге, произошла ошибка.  ',
  'serverError.description.COUNTRY_MIXED_MULTIPLES_ERROR': 'При попытке обработать список исходов, доступных для экспресс ставки в определенной стране, произошла ошибка.',
  'serverError.description.SPORT_MIXED_MULTIPLES_ERROR': 'При попытке обработать список исходов, доступных для экспресс ставки в определенном спорте, произошла ошибка.  ',
  'serverError.description.BET_LIMIT_WRONG_SETTINGS': 'Настройки, которые вы выбрали для максимальной суммы ставки, являются неправильными.',
  'serverError.description.INVALID_DYNAMIC_LIMIT': 'Следующий динамический лимит является недействительным.',
  'serverError.description.CATEGORY_MAPPING_NOT_FOUND': 'Маппинг категории не найден.',
  'serverError.description.SELECTION_SETTING_DOES_NOT_EXIST': 'Выбранный или введенный параметр исхода не существует или недоступен.',
  'serverError.description.SELECTION_COMBINATION_MIN_ERROR': 'Вам не хватает минимального количества комбинаций исходов для завершения вашего запроса.',
  'serverError.description.SELECTION_COMBINATION_MAX_ERROR': 'Вы достигли максимального количества комбинаций исходов.',
  'serverError.description.INVALID_CURRENCY': 'Введенная или выбранная валюта недействительна или не существует в системе.',
  'serverError.description.EVENT_SELECTION_SETTINGS_NOT_FOUND': 'Параметры, которые вы применили для следующего исхода события, не были найдены.',
  'serverError.description.EVENT_MARKET_SETTINGS_NOT_FOUND': 'Параметры, которые вы применили для следующей позиции события, не были найдены.',
  'serverError.description.INVALID_FIRST_NAME': 'Имя, которое вы ввели, недействительно.',
  'serverError.description.INVALID_LAST_NAME': 'Введенная вами фамилия недействительна.',
  'serverError.description.INVALID_BIRTHDAY': 'Введенный вами день рождения недействителен.',
  'serverError.description.INVALID_COUNTRY': 'Страна, которую вы ввели или выбрали, недействительна, поскольку мы не предоставляем там услуги.',
  'serverError.description.INVALID_ADDRESS': 'Введенный вами адрес недействителен.',
  'serverError.description.INVALID_CITY': 'Введенный вами город недействителен.',
  'serverError.description.INVALID_STATE': 'Введенный вами область или край недействительна или недействителен.',
  'serverError.description.INVALID_ZIP_CODE': 'Введенный вами почтовый индекс недействителен.',
  'serverError.description.INVALID_PHONE': 'Номер телефона, который вы ввели, недействителен.',
  'serverError.description.INVALID_PASSWORD': 'Пароль, который вы ввели, неверен. Он должен соответствовать параметрам, установленным веб-сайтом (6 символов, без тире, других символов и т. д.). ',
  'serverError.description.INVALID_ANSWER': 'Введенный вами ответ недействителен.',
  'serverError.description.INVALID_AGE_18': 'Введенный вами возраст недопустим. Вам должно быть не менее 21 года, чтобы зарегистрироваться на нашем сайте. ',
  'serverError.description.INVALID_SECRET': 'Введенный секрет недействителен.',
  // I'm here now
  'serverError.description.USER_ALREADY_EXISTS': 'Пользователь с теми же личными данными уже существует или пользователь с тем же именем, электронной почтой и / или именем пользователя уже существует.',
  'serverError.description.PHONE_ALREADY_EXISTS': 'Номер телефона, который вы ввели, уже существует в системе в личных данных другого пользователя.',
  'serverError.description.USERNAME_ALREADY_EXISTS': 'Имя пользователя, которое вы выбрали, уже используется другим пользователем.',
  'serverError.description.EMAIL_ALREADY_EXISTS': 'Введенный вами адрес электронной почты уже зарегистрирован другим пользователем на сайте.',
  'serverError.description.INVALID_QUESTION': 'Вопрос, который вы ввели, является недопустимым или неправильным.',
  'serverError.description.USER_HASH_IS_NOT_FOUND': 'Пользовательский хэш не найден в системе.',
  'serverError.description.USER_HASH_IS_EXPIRED': 'Срок использования, следующего хэша пользователя истек.',
  'serverError.description.EVENT_HAS_ACTIVE_BET': 'У следующего события уже есть активная ставка.',
  'serverError.description.EVENT_MARKET_HAS_ACTIVE_BET': 'У следующей позиции события уже есть активная ставка.',
  'serverError.description.EVENT_SELECTION_HAS_ACTIVE_BET': 'У следующего исхода события уже есть активная ставка.',
  'serverError.description.SMS_CODE_IS_INVALID': 'Введенный вами смс-код недействителен.',
  'serverError.description.SMS_CODE_IS_EXPIRED': 'СМС код больше не действителен, так как он истек.',
  'serverError.description.SMS_CODE_SENT': 'Смс-код был отправлен на ваш номер телефона.',
  'serverError.description.SMS_CODE_IS_OFF': 'Функциональность кода SMS отключена.',
  'serverError.description.EVENT_SETTINGS_DO_NOT_EXIST': 'Выбранные настройки событий не существуют в системе.',
  'serverError.description.MARKET_HAS_ACTIVE_BET': 'У следующей позиции уже есть активная ставка.',
  'serverError.description.USER_NOT_VERIFIED': 'Ваша учетная запись еще не подтверждена или следующий пользователь еще не был подтвержден нашим сайтом. ',
  'serverError.description.CURRENCY_NOT_SUPPORTED': 'Выбранная вами валюта не поддерживается системой.',
  'serverError.description.TRANSACTION_NOT_FOUND': 'Транзакция, которую вы ищете, не найдена в истории системной статистики.',
  'serverError.description.WRONG_WEBSITE_ID': 'ID веб-сайта, который вы ввели, неверен.',
  'serverError.description.PAYMENT_METHOD_NOT_SUPPORTED_FOR_THIS_WEBSITE': 'Данный способ оплаты (введенный вами способ оплаты) не поддерживается нашим сайтом.',
  'serverError.description.UNKNOWN_FILTER': 'Введенный вами фильтр неизвестен или не существует.',
  'serverError.description.INVALID_DOMAIN': 'Введенное вами имя домена недействительно или не существует. Повторите попытку после проверки орфографии.',
  'serverError.description.BET_IS_NOT_IN_REVIEW': 'Следующая ставка еще не в процессе рассмотрения.',
  'serverError.description.INVALID_STATUS': 'Выбранный вами статус недействителен.',
  'serverError.description.SCOPE_OR_STAT_NOT_FOUND': 'Мы не смогли найти требуемые область применения или статус.',
  'serverError.description.PAYMENT_NOT_FOUND': 'Способ оплаты, который вы ищете, не найден.',
  'serverError.description.WEBSITE_NOT_FOUND': 'Веб-сайт, который вы ищете не найден. Проверьте название веб-сайта или, если оно правильно, убедитесь, что сайт не был удален навсегда.',
  'serverError.description.PAYMENT_DOES_NOT_SUPPORT_SELECTED_CURRENCY': 'Выбранная валюта не поддерживается и недоступна для обработки требуемого платежа.',
  'serverError.description.INVALID_IP': 'Ваш IP-адрес недействителен или недопустимый IP-адрес.',
  'serverError.description.COMMUNICATION_ERROR': 'При попытке обработать ваш запрос произошла ошибка связи.',
  'serverError.description.PURSE_NOT_FOUND': 'Кошелек, который вы ищете, не найден.',
  'serverError.description.BANNER_ID_MISSING': 'ID баннера отсутствует. Его необходимо добавить. ',
  'serverError.description.INVALID_REGISTRATION': 'Процесс регистрации не был успешным и был признан недействительным.',
  'serverError.description.INVALID_PAYMENT_DETAILS': 'Введенные вами данные о платеже недействительны.',
  'serverError.description.INSUFFICIENT_MERCHANT_FUNDS': 'У вас недостаточно средств, чтобы продолжить запрос.',
  'serverError.description.SOME_ELSE_EVENT_AT_THIS_TIME_SELECTED': 'На это время уже выбрано другое событие.',
  'serverError.description.SESSION_NOT_FOUND': 'Сессия, необходимая для обработки вашего запроса, не найдена.',
  'serverError.description.CASINO_GAME_NOT_FOUND': 'Казино игра, которую вы ищете, не найдена или не существует на веб-сайте.',
  'serverError.description.PAYMEGA_API_AUTH_ERROR': 'При попытке обработать ваш запрос произошла ошибка аутентификации Paymega API.',
  'serverError.description.PAYMEGA_API_SETTLE_ERROR': 'При попытке обработать ваш запрос на Paymega произошла ошибка расчета API.',
  'serverError.description.TRANSACTION_AUTH_FAILED': 'Системе не удалось выполнить аутентификацию вашей транзакции. Повторите попытку, проверив личные и другие важные данные, которые вы указали.',
  'serverError.description.TRANSACTION_SETTLE_FAILED': 'Системе не удалось выполнить расчет вашей транзакции. Повторите попытку, проверив личные и другие важные данные, которые вы указали. ',
  'serverError.description.TRANSACTION_CHECK_FAILED': 'Системе не удалось выполнить проверку вашей транзакции. Повторите попытку, проверив личные и другие важные данные, которые вы указали.  ',
  'serverError.description.TRANSACTION_VOID_FAILED': 'Системе не удалось выполнить аннулирование вашей транзакции.',
  'serverError.description.UNKNOWN_DOMAIN': 'Имя домена, которое вы ввели, неизвестно.',
  'serverError.description.UNKNOWN_EMAIL_TEMPLATE': 'Шаблон электронной почты, который вы ищете, неизвестен или не существует.',
  'serverError.description.CASINO_ID_IS_INVALID': 'ID казино, который вы ввели, недействителен или не существует.',
  'serverError.description.PASSWORD_LENGTH_6': 'Ваш пароль должен содержать не менее 6 символов.',

  'serverError.description.INVALID_TRANSACTION_DETAILS': 'Сведения о транзакции, которые вы указали, являются недопустимыми. Пожалуйста, проверьте их и повторите попытку',
  'serverError.description.PHONE_VERIFICATION_FAILED': 'Процедура проверки вашего номера телефона не удалась. Вы либо указали неправильный номер телефона, либо ввели неправильный код. Пожалуйста, попробуйте еще раз',
  'serverError.description.WITHDRAW_MIN_LIMIT': 'Сумма, которую вы ввели, меньше минимально допустимой суммы вывода',
  'serverError.description.WITHDRAW_MAX_LIMIT': 'Мы не можем обработать ваш запрос, потому что введенная вами сумма превышает максимально допустимую сумму вывода',
  'serverError.description.DEPOSIT_MAX_LIMIT': 'Вы достигли максимального объема депозита, который вы можете сделать за один раз. Пожалуйста, введите меньшую сумму',
  'serverError.description.DEPOSIT_MIN_LIMIT': 'Сумма, которую вы ввели, меньше разрешенной суммы минимального депозита',
  'serverError.description.REGISTRATION_EMAIL_SEND_BUT_NOT_VERIFIED': 'Электронная почта регистрации уже отправлена вам, но вы еще не подтвердили ее',
  'serverError.description.ACTIVE_BETS_ON_EVENT': 'Мы не можем обработать ваш запрос, потому что на этом событии все еще активны ставки',
  'serverError.description.VERIFIED_DOCUMENT_CANNOT_BE_DELETED': 'Этот документ был подтвержден веб-сайтом и не может быть удален',
  'serverError.description.FIELD_IS_BLOCKED_TO_EDIT': 'Вы не можете редактировать следующее поле, потому что оно было заблокировано',
  'serverError.description.INVALID_SOCIAL_ID': 'ID введенный для следующего социального сайта, недействителен',

  'serverError.description.EVENT_MARKET_MAX_WINNERS': 'Ваш запрос не может быть обработан, потому что на следующей позиции событий максимальное количество победителей',
  'serverError.description.DOCUMENT_WAS_DELETED_BY_USER': 'Документ, который вы пытаетесь открыть, был удален пользователем',
  'serverError.description.AGE_FROM_IS_NOT_NUMBER': 'Начальный возраст может быть введен только в цифрах',
  'serverError.description.AGE_FROM_IS_LESS_THAN_18': 'Начальный возраст должен быть 18 и выше. Возраст, который вы ввели, ниже 18',
  'serverError.description.AGE_TO_IS_NOT_NUMBER': 'Поле ввода максимального возраста может быть заполнено только цифрами',
  'serverError.description.AGE_TO_IS_NOT_BETWEEN_18_AND_100': 'Максимальный возраст должен быть чем-то между 18 и 100. Возраст, который вы ввели, не соответствует этой шкале',
  'serverError.description.AGE_TO_IS_LESS_THAN_AGE_FROM': 'Максимальный возраст не может быть меньше, чем начальный возраст, пожалуйста, проверьте свои данные',
  'serverError.description.INVALID_DATE': 'Дата, указанная вами, недействительна, повторите попытку',
}